// A small song description -> hUGEDriver song data (C). Phase 7 replaces the source with .uge files,
// but the output shape stays the same.
//
// Song: { tempo (ticks per row), rows (per pattern, default 64), duty: [{ duty 0-3, env }], wave: [{ volume 1-3, wave }],
//         noise: [{ env }], waves: [[32 nibbles]], patterns: { name: { p1, p2, wave, noise } }, order: [names] }
// A channel is bars of space-separated rows: "C5" plays a note with the channel's first instrument,
// "C5:2" picks instrument 2 (or "C5:lead", a name from dutyNames / waveNames), "." holds, "-" cuts the
// note, and "~047" after a row adds an effect (here an arpeggio; "~f07" sets the speed). Noise rows use
// the names in drums: { k: ['C5', 1] }.
'use strict';
const NOTES = { C: 0, 'C#': 1, D: 2, 'D#': 3, E: 4, F: 5, 'F#': 6, G: 7, 'G#': 8, A: 9, 'A#': 10, B: 11 };
const HOLD = 90;

function note(name) {
  const m = /^([A-G]#?)(\d)$/.exec(name); if (!m) throw new Error(`bad note ${name}`);
  const n = (+m[2] - 3) * 12 + NOTES[m[1]];
  if (n < 0 || n > 71) throw new Error(`note ${name} is outside C3-B8`);
  return n;
}
// one hUGE row: note, instrument (1-based, 0 = keep) and a 12-bit effect
const row = (n, ins, fx) => [(n | ((ins & 0x10) << 3)) & 0xff, (((ins << 4) & 0xff) | (fx >> 8)) & 0xff, fx & 0xff];

function channelRows(src, rows, defIns, drums, insNames = []) {
  const toks = (src || '').trim().split(/\s+/).filter(Boolean);
  while (toks.length < rows) toks.push('.');
  if (toks.length > rows) throw new Error(`pattern has ${toks.length} rows, max ${rows}`);
  return toks.map(tok => {
    const [t, fxs] = tok.split('~'), fx = fxs ? parseInt(fxs, 16) : 0;
    if (t === '.') return row(HOLD, 0, fx);
    if (t === '-') return row(HOLD, 0, 0xE00);   // Exx: cut the note after xx ticks
    if (drums && drums[t]) { const [n, ins] = drums[t]; return row(note(n), ins, fx); }
    const [n, ins] = t.split(':');
    const i = ins === undefined ? defIns : /^\d+$/.test(ins) ? +ins : insNames.indexOf(ins) + 1;
    if (!i) throw new Error(`unknown instrument ${ins}`);
    return row(note(n), i, fx);
  });
}

function compile(name, song) {
  const rows = song.rows || 64, pats = [], index = {};
  const chans = [['p1', 1], ['p2', 2], ['wave', 1], ['noise', 1]];
  const orders = chans.map(([ch, ins]) => song.order.map(pn => {
    const key = ch + '|' + (song.patterns[pn][ch] || '');   // a pattern that repeats is stored once
    const names = ch === 'wave' ? song.waveNames : ch === 'noise' ? song.noiseNames : song.dutyNames;
    if (!(key in index)) { index[key] = pats.length; pats.push(channelRows(song.patterns[pn][ch], rows, ins, ch === 'noise' ? song.drums : null, names)); }
    return 'P' + index[key];
  }));
  const pad = (arr, n, fill) => arr.concat(Array(Math.max(0, n - arr.length)).fill(fill));
  const duty = pad((song.duty || []).map(d => `{8, ${(d.duty & 3) << 6}, ${d.env}, 0, 128}`), 15, '{8, 128, 240, 0, 128}');
  const wave = pad((song.wave || []).map(w => `{0, ${[0, 32, 64, 96][w.volume || 1]}, ${w.wave || 0}, 0, 128}`), 15, '{0, 32, 0, 0, 128}');
  const noise = pad((song.noise || []).map(n => `{${n.env}, 0, 0, 0, 0}`), 15, '{240, 0, 0, 0, 0}');
  const waves = pad((song.waves || []).map(w => { const b = []; for (let i = 0; i < 32; i += 2) b.push((w[i] << 4) | w[i + 1]); return b.join(', '); }), 16, Array(16).fill(0).join(', '));
  const hex = b => b.map(v => '0x' + v.toString(16).padStart(2, '0')).join(',');
  return `// Generated by gbc/tools/build.js from gbc/music/${name}.js. Do not edit.
#pragma bank 255
#include <gb/gb.h>
#include "hUGEDriver.h"
#include <stddef.h>

BANKREF(song_${name})
static const unsigned char order_cnt = ${song.order.length * 2};
${pats.map((p, i) => `static const unsigned char P${i}[] = {\n  ${p.map(hex).join(',\n  ')}\n};`).join('\n')}
${orders.map((o, i) => `static const unsigned char* const order${i + 1}[] = {${o.join(', ')}};`).join('\n')}
static const hUGEDutyInstr_t duty_instruments[] = {\n  ${duty.join(',\n  ')}\n};
static const hUGEWaveInstr_t wave_instruments[] = {\n  ${wave.join(',\n  ')}\n};
static const hUGENoiseInstr_t noise_instruments[] = {\n  ${noise.join(',\n  ')}\n};
static const unsigned char waves[] = {\n  ${waves.join(',\n  ')}\n};
const hUGESong_t song_${name} = {${song.tempo}, &order_cnt, order1, order2, order3, order4, duty_instruments, wave_instruments, noise_instruments, NULL, waves};
`;
}
module.exports = { compile, note };
