// Fang the Fox — world data. Maps are 14x8; door / npc / sign keys are 0-based tile indexes (row * 14 + col).
//
// Map legend
//   _ floor    F start      d door       D secret door (Pathfinder)   T tree     r rock     b brick    n snow wall
//   y basalt   w water      i ice        l lava       v steam vent   e vines    o fog      x snowdrift
//   p portal (decor)        * brazier    # puzzle gate  % locked gate (Ancient Key)       @ pushable block
//   + pressure plate        ~ void pit   u crumbling floor              = bridge   & NPC (see npcs)   ? sign (see signs)
//   Monsters and items: see MONSTERS / ITEMS keys.

const GAME_VERSION = '1.0.0';
const MUSIC_BASE = 'https://f001.backblazeb2.com/file/Ginder/Music/Tiny%20Bit%20Adventures/';
const TRACKS = {
  title:  '01-Fang The Fox',
  battle: '02-Collaborative Attacks',
  dream:  '03-Dreamspace',
  blitz:  '04-Run and Blitz',
  void:   '05-Avoid The Void',
  win:    '06-Again, Again, Win',
  forest: '07-Forest Exploration',
  slims:  '08-Slim Monsters',
  plasma: '09-Plasma Blast',
  home:   '10-Forest Home',
};

const MONSTERS = {
  s: { name: 'Slim',            spr: 'slim',       hp: 9,   atk: 3,  xp: 15 },
  S: { name: 'Big Slim',        spr: 'bigslim',    hp: 15,  atk: 5,  xp: 30 },
  g: { name: 'Goo Monster',     spr: 'goo',        hp: 40,  atk: 7,  xp: 70 },
  W: { name: 'Wolf',            spr: 'wolf',       hp: 20,  atk: 6,  xp: 40, interval: 2 },
  P: { name: 'Spider',          spr: 'spider',     hp: 12,  atk: 4,  xp: 25, poison: 3 },
  B: { name: 'Bat',             spr: 'bat',        hp: 8,   atk: 3,  xp: 20, steps: 2, flies: true },
  G: { name: 'Golem',           spr: 'golem',      hp: 50,  atk: 10, xp: 100, dormant: true },
  K: { name: 'Skeleton',        spr: 'skeleton',   hp: 25,  atk: 7,  xp: 50, revives: true },
  I: { name: 'Ice Sprite',      spr: 'icesprite',  hp: 18,  atk: 8,  xp: 35, shatter: true, flies: true },
  E: { name: 'Frost Bear',      spr: 'frostbear',  hp: 55,  atk: 12, xp: 80, charge: true },
  Z: { name: 'Blizzard Wisp',   spr: 'wisp',       hp: 25,  atk: 7,  xp: 45, trail: 'i', flies: true },
  V: { name: 'Fire Elemental',  spr: 'fireelem',   hp: 30,  atk: 10, xp: 50, fireproof: true, flies: true },
  M: { name: 'Magma Salamander',spr: 'salamander', hp: 40,  atk: 11, xp: 65, trail: 'l' },
  O: { name: 'Lava Golem',      spr: 'lavagolem',  hp: 80,  atk: 14, xp: 120, armored: true },
  J: { name: 'Sprite',          spr: 'fairy',      hp: 15,  atk: 5,  xp: 30, healer: 5, flies: true },
  N: { name: 'Treant',          spr: 'treant',     hp: 65,  atk: 11, xp: 90, camo: true },
  U: { name: 'Dream Moth',      spr: 'moth',       hp: 20,  atk: 9,  xp: 55, sleeper: true, flies: true },
  R: { name: 'Toxic Shroom',    spr: 'shroom',     hp: 28,  atk: 8,  xp: 60, explodes: true },
  z: { name: 'Void Wisp',       spr: 'voidwisp',   hp: 60,  atk: 16, xp: 110, flies: true, steps: 2 },
  q: { name: 'Shadow Slim',     spr: 'shadowslim', hp: 80,  atk: 17, xp: 130, splits: true },
  // Bosses. Each guards one of the five Embers.
  j: { name: 'Goo King',        spr: 'gooking',    hp: 110, atk: 7,  xp: 250, boss: true, summon: 's', spawnEvery: 3, drop: ['ember_forest'] },
  X: { name: 'Ancient Guardian',spr: 'guardian',   hp: 200, atk: 12, xp: 500, boss: true, summon: 'K', drop: ['ember_stone'] },
  Y: { name: 'Ice Colossus',    spr: 'colossus',   hp: 250, atk: 16, xp: 600, boss: true, summon: 'I', drop: ['ember_frost', '5'] },
  Q: { name: 'Volcanic Dragon', spr: 'dragon',     hp: 300, atk: 18, xp: 750, boss: true, breath: true, drop: ['ember_flame', '6'] },
  t: { name: 'Rotheart',        spr: 'rotheart',   hp: 340, atk: 19, xp: 900, boss: true, summon: 'R', rootsnare: true, drop: ['ember_life'] },
  A: { name: 'The Primordial',  spr: 'primordial', hp: 520, atk: 22, xp: 2000, boss: true, final: true, summon: 'z', phases: 3, drop: [] },
};

const ITEMS = {
  f: { name: 'Fish',          spr: 'fish' },
  H: { name: 'Golden Fish',   spr: 'goldfish' },
  m: { name: 'Mushroom',      spr: 'mushroom' },
  c: { name: 'Crystal Shard', spr: 'crystal' },
  k: { name: 'Ancient Key',   spr: 'key' },
  a: { name: 'Relic',         spr: 'artifact' },
  C: { name: 'Chest',         spr: 'chest' },
  L: { name: 'Locked Chest',  spr: 'chest_locked' },
  '1': { name: 'Antidote',    spr: 'antidote' },
  '2': { name: 'Barrier',     spr: 'barrier' },
  '3': { name: 'Haste',       spr: 'haste' },
  '4': { name: 'True Sight',  spr: 'scroll' },
  '5': { name: 'Frost Cloak', spr: 'cloak' },
  '6': { name: 'Dragon Scale',spr: 'scale' },
  '8': { name: 'Heart Container', spr: 'heart' },
  '9': { name: 'Crystal Key', spr: 'crystal_key' },
  ember_forest: { name: 'Forest Ember', spr: 'ember_forest', ember: true },
  ember_stone:  { name: 'Stone Ember',  spr: 'ember_stone',  ember: true },
  ember_frost:  { name: 'Frost Ember',  spr: 'ember_frost',  ember: true },
  ember_flame:  { name: 'Flame Ember',  spr: 'ember_flame',  ember: true },
  ember_life:   { name: 'Life Ember',   spr: 'ember_life',   ember: true },
};
const EMBERS = ['ember_forest', 'ember_stone', 'ember_frost', 'ember_flame', 'ember_life'];

const TERRAIN = {
  T: { solid: true, tree: true }, r: { solid: true, spr: 'rock' }, b: { solid: true, spr: 'brick' },
  n: { solid: true, spr: 'snowwall' }, y: { solid: true, spr: 'basalt' }, w: { solid: true, water: true },
  i: { hazard: 'ice' }, l: { hazard: 'lava' }, v: { hazard: 'vent' }, e: { hazard: 'vines' },
  o: { hazard: 'fog' }, x: { hazard: 'snowdrift' }, p: { solid: true, portal: true },
  '*': { solid: true, spr: 'brazier_off' }, '#': { solid: true, spr: 'gate' }, '%': { solid: true, spr: 'lockgate' },
  '~': { void: true }, u: { hazard: 'crumble' }, '=': {}, '+': {}, '?': { solid: true, spr: 'sign' },
};

const PERKS = {
  flameBurst:    { name: 'Flame Burst',    tree: 'Combat',    desc: 'Hits splash to enemies next to your target.' },
  criticalStrike:{ name: 'Critical Strike',tree: 'Combat',    desc: '20% chance to deal double damage.' },
  fury:          { name: 'Fury',           tree: 'Combat',    desc: '+3 attack while below 30% health.' },
  fireSpin:      { name: 'Fire Spin',      tree: 'Combat',    desc: 'SPACE: burn every adjacent enemy. 4 turn cooldown.' },
  thickFur:      { name: 'Thick Fur',      tree: 'Survival',  desc: 'Take 1 less damage from every hit.' },
  scavenger:     { name: 'Scavenger',      tree: 'Survival',  desc: 'Fish heal 50% more.' },
  regeneration:  { name: 'Regeneration',   tree: 'Survival',  desc: 'Heal 1 HP every 4 turns.' },
  secondWind:    { name: 'Second Wind',    tree: 'Survival',  desc: 'Survive one fatal hit per area at 1 HP.' },
  keenEyes:      { name: 'Keen Eyes',      tree: 'Explore',   desc: 'See through fog and camouflage.' },
  swiftFeet:     { name: 'Swift Feet',     tree: 'Explore',   desc: 'Enemies act every 4 turns instead of 3.' },
  treasureHunter:{ name: 'Treasure Hunter',tree: 'Explore',   desc: 'Chests hold an extra gem and 5 fish.' },
  pathfinder:    { name: 'Pathfinder',     tree: 'Explore',   desc: 'Open overgrown secret passages.' },
  frostTouch:    { name: 'Frost Touch',    tree: 'Elemental', desc: '20% chance to freeze a foe for 2 turns.' },
  heatResist:    { name: 'Heat Resist',    tree: 'Elemental', desc: 'Lava and fire hurt half as much.' },
  natureBond:    { name: 'Nature Bond',    tree: 'Elemental', desc: 'Vines never hold you.' },
};

// Rudy's wares. once: can only be bought one time.
const SHOP = [
  { id: 'fish',   name: '5 Fish',          cost: 1, desc: 'A bundle of fresh fish.' },
  { id: 'barrier',name: 'Barrier Potion',  cost: 2, desc: 'Blocks the next 3 hits.' },
  { id: 'haste',  name: 'Haste Potion',    cost: 2, desc: 'Enemies slow down for 12 turns.' },
  { id: 'key',    name: 'Ancient Key',     cost: 4, desc: 'Opens one locked chest.' },
  { id: 'heart',  name: 'Heart Container', cost: 6, desc: '+20 max health.', once: true },
  { id: 'claws',  name: 'Sharp Claws',     cost: 8, desc: '+3 attack, forever.', once: true },
];

const BIOMES = {
  night:    { ground: ['grass', 3], sky: ['#0a0e22', '#141b3a', '#1f2a52', '#2a3868'], moon: true, clouds: '#3a4a78', rain: true, dark: 0.52, ambient: '#070a1c', under: 'earth', falls: true, horizon: 'hills', tree: 'tree' },
  burrow:   { ground: ['dirt', 2],  sky: ['#120a14', '#1e1020', '#2c1a28', '#3a2430'], fireflies: true, clouds: '#3a2838', dark: 0.5, ambient: '#0c0610', under: 'earth', horizon: 'roots', tree: 'tree' },
  pond:     { ground: ['grass', 3], sky: ['#081418', '#0e2228', '#163238', '#20444a'], moon: true, clouds: '#2a4a50', fireflies: true, rain: 'light', dark: 0.5, ambient: '#04100c', under: 'earth', falls: true, horizon: 'pines', tree: 'tree' },
  grotto:   { ground: ['moss', 2],  sky: ['#04100a', '#0a1c12', '#10281a', '#163422'], clouds: null, motes: '#9be06a', dark: 0.6, ambient: '#020a04', under: 'mossy', horizon: 'roots', tree: 'tree' },
  lake:     { ground: ['grass', 3], sky: ['#0a1022', '#122040', '#1c3058', '#284070'], moon: true, clouds: '#3c5078', rain: 'light', dark: 0.5, ambient: '#060c1c', under: 'earth', falls: true, horizon: 'hills', tree: 'tree' },
  woods:    { ground: ['grass', 3], sky: ['#060c12', '#0c1820', '#12242c', '#1a3036'], moon: 'dim', clouds: '#1e3038', fireflies: true, fog: true, dark: 0.62, ambient: '#030a0c', under: 'earth', horizon: 'pines', tree: 'tree_b' },
  cave:     { ground: ['cave', 2],  sky: ['#04050c', '#080a18', '#0e1024', '#141830'], stars: true, clouds: null, motes: '#6fe8f0', dark: 0.64, ambient: '#02030a', under: 'rock', horizon: 'crystals', tree: 'tree' },
  ruins:    { ground: ['ruin', 2],  sky: ['#0c0818', '#1a1030', '#281848', '#34205a'], moon: true, clouds: '#3a2a5a', rain: true, lightning: true, dark: 0.55, ambient: '#08041a', under: 'rock', horizon: 'ruins', tree: 'tree_dead' },
  nexus:    { ground: ['dream', 2], sky: ['#0a0418', '#1a0a34', '#2a1050', '#3a1a6a'], stars: true, nebula: true, clouds: null, motes: '#a86ad8', dark: 0.42, ambient: '#0a0420', under: 'crystal', horizon: 'isles', tree: 'tree_magic' },
  frozen:   { ground: ['snow', 2],  sky: ['#040c18', '#0a1a2e', '#123048', '#1a4260'], moon: true, stars: true, aurora: true, clouds: '#4a6a8a', snow: true, dark: 0.36, ambient: '#04101e', under: 'ice', horizon: 'peaks', tree: 'tree_snow' },
  volcanic: { ground: ['ash', 2],   sky: ['#100404', '#240808', '#3a0c08', '#58160a'], redmoon: true, clouds: '#4a1a14', embers: true, dark: 0.5, ambient: '#120204', under: 'basalt', horizon: 'volcanoes', tree: 'tree_dead' },
  enchanted:{ ground: ['moss', 2],  sky: ['#060a14', '#0e1428', '#1a1a3c', '#2a1c4a'], moon: true, stars: true, clouds: '#2a2a50', fireflies: true, spores: true, fog: true, dark: 0.5, ambient: '#06040e', under: 'mossy', falls: true, horizon: 'pines', tree: 'tree_magic' },
  dream:    { ground: ['dream', 2], sky: ['#10081c', '#201038', '#301a52', '#42246a'], stars: true, nebula: true, clouds: '#4a2a6a', motes: '#ffa0d0', dark: 0.45, ambient: '#0c0418', under: 'crystal', horizon: 'isles', tree: 'tree_magic' },
  void:     { ground: ['dream', 2], sky: ['#020104', '#06030c', '#0a0614', '#0e0a1c'], stars: true, clouds: null, motes: '#6b3a9a', dark: 0.72, ambient: '#010006', under: 'crystal', horizon: 'isles', tree: 'tree_dead' },
};

// Area props: [sprite, x, y] in canvas pixels, anchored bottom-centre (y=60 is the back edge of the grid).
// pos: where the island sits on the world map (0-384 x 0-200).
const AREAS = {
  // ───────────── Act I: Forest Home ─────────────
  home: {
    title: 'Forest Home', biome: 'night', music: 'home', region: 'Forest Home', pos: [118, 120],
    map: [
      'F_T_TTT__&___a',
      '_T?__T______d_',
      '_T_T__T__ff___',
      '___fC_________',
      '______________',
      '_T__________s_',
      '_T_TT_________',
      'TTTww___s____d',
    ],
    doors: {
      111: { to: 'fox_hole', spawn: 96, name: 'Into the fox hole', style: 'hole' },
      26:  { to: 'lake_tower', name: 'Off to Lake Tower', style: 'hole' },
      63:  { to: 'elemental_portal', spawn: 111, name: 'Through the portal to the Sky Nexus', style: 'portal', when: 'guardian' },
    },
    npcs: { 9: 'grandma' },
    kitSpots: [53, 54, 67, 68, 55],
    signs: { 16: "Fang's cottage. Bump into things to talk, open or fight. F eats a fish. P shows the map." },
    props: [['tree_dead', 118, 60], ['lantern', 132, 60], ['house', 250, 60], ['hearth', 196, 60], ['gravestone', 160, 60],
            ['pumpkin', 72, 100], ['lantern', 72, 140], ['pumpkin', 312, 76], ['gravestone', 312, 120], ['pumpkin', 72, 186], ['fence', 296, 60], ['pumpkin', 312, 170]],
  },
  fox_hole: {
    title: 'Fox Hole', biome: 'burrow', music: 'home', region: 'Forest Home', pos: [118, 150],
    map: [
      '______________',
      '?___________C_',
      '__a__TTTs_____',
      'd____T__S_____',
      '_s___TTTs_____',
      '______________',
      '____________d_',
      'T_____f_______',
    ],
    doors: {
      96: { to: 'home', spawn: 111, name: 'Back home', style: 'hole' },
      42: { to: 'slime_pond', spawn: 96, name: 'West to the Slime Pond', style: 'hole' },
      48: { to: 'dreamspace', name: 'Into the Void Rift...', style: 'rift', when: 'hearth' },
    },
    signs: { 14: 'Slime Pond: west. Something big has been oozing about down there...' },
    props: [['burrow', 120, 60], ['lantern', 150, 60], ['lantern', 250, 60], ['bush', 200, 60], ['lantern', 72, 120], ['lantern', 312, 120], ['bush', 280, 60]],
  },
  slime_pond: {
    title: 'Slime Pond', biome: 'pond', music: 'slims', region: 'Forest Home', pos: [80, 150],
    map: [
      'sss____SsS__a_',
      'ss____wwsww___',
      '______wwsww__&',
      'd____wwwwwww__',
      '_____wwwww____',
      '__?__wwwww_C__',
      '______wwww__d_',
      '_____f_wwww___',
    ],
    doors: {
      96: { to: 'fox_hole', spawn: 42, name: 'Back to the fox hole', style: 'hole' },
      42: { to: 'goo_grotto', name: "Into the Goo King's grotto", style: 'hole' },
    },
    npcs: { 41: 'kit1' },
    signs: { 72: "Goo Grotto, west. Beware the Goo King! He's been flooding the forest with slime." },
    props: [['tree', 100, 60], ['tree_b', 150, 60], ['bush', 220, 60], ['tree', 290, 60], ['tree', 72, 120], ['bush', 312, 150]],
  },
  goo_grotto: {
    title: 'Goo Grotto', biome: 'grotto', music: 'battle', region: 'Forest Home', pos: [44, 150], boss: true,
    map: [
      'TTTww____wwTTT',
      'T__w_s____w__T',
      'T_s_______s__T',
      'dF_____j_____T',
      'T_____________',
      'T__s______s__T',
      'T__w_______wfT',
      'TTTww_a__wwTTT',
    ],
    doors: { 42: { to: 'slime_pond', spawn: 42, name: 'Back to the Slime Pond', style: 'hole' } },
    props: [['shroom_big', 110, 60], ['bush', 160, 60], ['shroom_big', 240, 60], ['bush', 290, 60], ['shroom_big', 72, 150], ['shroom_big', 312, 110]],
  },
  lake_tower: {
    title: 'Lake Tower', biome: 'lake', music: 'slims', region: 'Forest Home', pos: [160, 96],
    map: [
      '__?____SsS___&',
      '______wwsww_C_',
      '___a__wwswww__',
      'd____wwwwwww__',
      '_____wwwww____',
      '__f__wwwww____',
      '______wwww__d_',
      '______wwww____',
    ],
    doors: {
      42: { to: 'home', spawn: 26, name: 'Back home', style: 'hole' },
      96: { to: 'dark_woods', name: 'Into the Dark Woods', style: 'hole', req: 'gooking' },
    },
    npcs: { 13: 'hoot' },
    signs: { 2: 'Lake Tower. Home of Hoot, keeper of old stories. Bring him any relics you find.' },
    props: [['tower', 212, 60], ['tree', 100, 60], ['tree_b', 280, 60], ['lantern', 72, 90], ['bush', 312, 90], ['lantern', 312, 150]],
  },
  // ───────────── Act II: The Deep Woods ─────────────
  dark_woods: {
    title: 'Dark Woods', biome: 'woods', music: 'forest', region: 'Deep Woods', pos: [196, 96],
    map: [
      'TT_W_TTT__TTTT',
      'T_____T__P_TaT',
      '__T_?____&___T',
      'd___T__PT____d',
      '____TT____T_W_',
      'T_m__T___TT_C_',
      'TT_____W____D_',
      'TTT_f________T',
    ],
    doors: {
      42: { to: 'lake_tower', spawn: 96, name: 'Back to Lake Tower', style: 'hole' },
      55: { to: 'hollow_path', name: 'Deeper into the woods', style: 'hole' },
      96: { to: 'secret_den', name: 'A hidden den!', style: 'hole', req: 'pathfinder' },
    },
    npcs: { 37: 'rudy' },
    signs: { 32: "Rudy's Wares: gems for goods! The Hollow Path leads east to the Crystal Cave." },
    props: [['tree', 96, 60], ['tent', 160, 60], ['tree', 230, 60], ['tree_b', 290, 60], ['tree', 72, 110], ['tree_b', 312, 110], ['tree', 312, 180]],
  },
  secret_den: {
    title: 'Secret Den', biome: 'burrow', music: 'forest', region: 'Deep Woods', pos: [214, 124],
    map: [
      'TTTTTTTTTTTTTT',
      'T__P_____P__CT',
      'T_____TT_____T',
      'T__TT_T8T_TT_T',
      'T____________T',
      'TP__T_____P__T',
      'd_____a_____HT',
      'TTTTTTTTTTTTTT',
    ],
    doors: { 84: { to: 'dark_woods', spawn: 96, name: 'Back to the Dark Woods', style: 'hole' } },
    props: [['lantern', 110, 60], ['burrow', 192, 60], ['lantern', 274, 60]],
  },
  hollow_path: {
    title: 'Hollow Path', biome: 'woods', music: 'forest', region: 'Deep Woods', pos: [232, 96],
    map: [
      'TTTTTTTTTTTTTT',
      'T*___W___T___T',
      'T__TT____T_?_T',
      'd_?_T__*_#___d',
      'T___T____#___T',
      'T_TTT_P__T_&_T',
      'T*_______T__aT',
      'TTTTTTTTTTTTTT',
    ],
    doors: {
      42: { to: 'dark_woods', spawn: 55, name: 'Back to the Dark Woods', style: 'hole' },
      55: { to: 'crystal_cave', name: 'Down into the Crystal Cave', style: 'hole' },
    },
    npcs: { 81: 'kit2' },
    signs: { 44: 'Old braziers line the path. Only a fire fox can wake them. Light all three.', 39: 'Crystal Cave: east.' },
    props: [['tree', 96, 60], ['tree_dead', 150, 60], ['tree', 210, 60], ['tree_b', 270, 60], ['tree', 72, 130], ['tree_b', 312, 130]],
  },
  crystal_cave: {
    title: 'Crystal Cave', biome: 'cave', music: 'dream', region: 'Deep Woods', pos: [268, 96],
    map: [
      'rrrrrr_d_rrrrr',
      'r_c____B___c_r',
      'r___B_____G__r',
      'd______c___C_r',
      'r__G_____B__ar',
      'r____c___?___r',
      'r_B_________d_',
      'rrrrrr_H_rrrrr',
    ],
    doors: {
      42: { to: 'hollow_path', spawn: 55, name: 'Back to the Hollow Path', style: 'arch' },
      96: { to: 'crystal_depths', name: 'Down into the Crystal Depths', style: 'arch' },
      7:  { to: 'ancient_ruins', name: 'The Crystal Key fits! Into the Ancient Ruins', style: 'arch', req: 'crystalKey' },
    },
    signs: { 79: 'The great arch north is sealed with crystal. Its key rests somewhere in the Depths below.' },
    props: [['crystal_big', 100, 60], ['crystal_big', 150, 60], ['crystal_big', 250, 60], ['crystal_big', 72, 130], ['crystal_big', 312, 90]],
  },
  crystal_depths: {
    title: 'Crystal Depths', biome: 'cave', music: 'dream', region: 'Deep Woods', pos: [268, 124],
    map: [
      'rrrrrrrrrrrrrr',
      'r_____B____r_r',
      'r__@___+___#_r',
      'd__________r9r',
      'r__@___+___r_r',
      'r_?___G____rrr',
      'r&___c___B___r',
      'rrrrrrrrrrrrrr',
    ],
    doors: { 42: { to: 'crystal_cave', spawn: 96, name: 'Back up to the Crystal Cave', style: 'arch' } },
    npcs: { 85: 'kit3' },
    signs: { 72: 'Two stones, two plates. Push the stones onto the plates. (Leave and return to reset them.)' },
    props: [['crystal_big', 110, 60], ['crystal_big', 192, 60], ['crystal_big', 274, 60], ['crystal_big', 72, 150], ['crystal_big', 312, 110]],
  },
  ancient_ruins: {
    title: 'Ancient Ruins', biome: 'ruins', music: 'battle', region: 'Deep Woods', pos: [304, 96], boss: true,
    map: [
      'bbbbb_____bbbb',
      'b_____K_K____b',
      'b_k________L_b',
      'dF_____X_____b',
      'b____________b',
      'b_L__K___K__ab',
      'b____________b',
      'bbbbbb_f_bbbbb',
    ],
    doors: {
      42: { to: 'crystal_cave', spawn: 7, name: 'Back to the Crystal Cave', style: 'arch' },
      49: { to: 'elemental_portal', spawn: 42, name: 'Through the portal to the Sky Nexus', style: 'portal', when: 'guardian' },
    },
    props: [['pillar', 104, 60], ['statue', 176, 60], ['statue', 208, 60], ['pillar', 280, 60], ['pillar', 72, 120], ['pillar', 312, 150]],
  },
  // ───────────── Act III: The Sky Realms ─────────────
  elemental_portal: {
    title: 'Sky Nexus', biome: 'nexus', music: 'dream', region: 'Sky Realms', pos: [196, 44],
    map: [
      '______________',
      '_____d___d____',
      '______________',
      'd______p______',
      '______________',
      '__?_&_____&___',
      '_______d______',
      '_____________d',
    ],
    doors: {
      19: { to: 'glacier_pass', name: 'To Glacier Pass', style: 'portal' },
      23: { to: 'magma_caverns', name: 'To the Magma Caverns', style: 'portal', req: 'frost_cloak' },
      91: { to: 'whispering_woods', name: 'To the Whispering Woods', style: 'portal', req: 'dragon_scale' },
      42: { to: 'ancient_ruins', spawn: 49, name: 'Back to the Ruins', style: 'portal' },
      111: { to: 'home', spawn: 63, name: 'Home to the Forest', style: 'portal' },
    },
    npcs: { 74: 'rudy', 80: 'lumen' },
    signs: { 72: 'North-west: Glacier Pass. North-east: Magma Caverns. South: Whispering Woods. South-east corner: home.' },
    props: [['icepillar', 120, 60], ['forge', 260, 60], ['shroom_big', 72, 150], ['shroom_big', 312, 110], ['crystal_big', 312, 180], ['crystal_big', 72, 90]],
  },
  glacier_pass: {
    title: 'Glacier Pass', biome: 'frozen', music: 'blitz', region: 'Sky Realms', pos: [118, 40],
    map: [
      'nnn_ii_I_ii_nn',
      'n___i_____i__n',
      '__I___xxx___a_',
      'dF___ix1xi_E__',
      '___Z_ixxxi____',
      'n___________Cn',
      'n_I_ii_Z_ii_d_',
      'nnn_________nn',
    ],
    doors: {
      42: { to: 'elemental_portal', spawn: 19, name: 'Back to the Nexus', style: 'portal' },
      96: { to: 'ice_caves', name: 'Into the Ice Caves', style: 'arch' },
    },
    props: [['tree_snow', 100, 60], ['icepillar', 170, 60], ['tree_snow', 250, 60], ['icepillar', 300, 60], ['tree_snow', 72, 120], ['icepillar', 312, 150]],
  },
  ice_caves: {
    title: 'Ice Caves', biome: 'frozen', music: 'blitz', region: 'Sky Realms', pos: [82, 40], slide: true,
    map: [
      'nnnnnnnnnnnnnn',
      'n_iiiiin_iii&n',
      'niiiniiiiiiiin',
      'd_iiiiiiinii_n',
      'niiniiiiiiiiin',
      'nii_iiiniiiiin',
      'niiiiiniii_iid',
      'nnnnnnnnnnnnnn',
    ],
    doors: {
      42: { to: 'glacier_pass', spawn: 96, name: 'Back to Glacier Pass', style: 'arch' },
      97: { to: 'frozen_throne', name: 'The Frozen Throne', style: 'arch' },
    },
    npcs: { 26: 'kit4' },
    props: [['icepillar', 110, 60], ['icepillar', 192, 60], ['icepillar', 274, 60], ['icepillar', 72, 150], ['icepillar', 312, 110]],
  },
  frozen_throne: {
    title: 'Frozen Throne', biome: 'frozen', music: 'battle', region: 'Sky Realms', pos: [46, 40], boss: true,
    map: [
      'nniiiiiiiiiinn',
      'n_i________i_n',
      'i____I___I___i',
      'dF_____Y_____i',
      'i____________i',
      'i___I_____I__i',
      'n_i____H____an',
      'nniiiiiiiiiinn',
    ],
    doors: { 42: { to: 'ice_caves', spawn: 97, name: 'Back to the Ice Caves', style: 'arch' } },
    props: [['icepillar', 120, 60], ['throne', 192, 60], ['icepillar', 264, 60], ['icepillar', 72, 140], ['icepillar', 312, 140]],
  },
  magma_caverns: {
    title: 'Magma Caverns', biome: 'volcanic', music: 'plasma', region: 'Sky Realms', pos: [274, 40],
    map: [
      'yyyll__v__llyy',
      'y__l__V_V__l_y',
      '__M__v___v__a_',
      'dF_____C___O__',
      '___V__lll_____',
      'y____vlllv__2y',
      'y_M_________d_',
      'yyyl___f___lyy',
    ],
    doors: {
      42: { to: 'elemental_portal', spawn: 23, name: 'Back to the Nexus', style: 'portal' },
      96: { to: 'lava_bridges', name: 'Onto the Lava Bridges', style: 'arch' },
    },
    props: [['volcano_vent', 110, 60], ['tree_dead', 160, 60], ['volcano_vent', 240, 60], ['tree_dead', 290, 60], ['volcano_vent', 72, 130], ['volcano_vent', 312, 100]],
  },
  lava_bridges: {
    title: 'Lava Bridges', biome: 'volcanic', music: 'plasma', region: 'Sky Realms', pos: [310, 40], brazierTime: 20, crumbleTo: 'l',
    map: [
      'yyyyyyyyyyyyyy',
      'y*_?lllllll_*y',
      'y___=======__y',
      'd__vlllllll_#d',
      'y___uuuuuuu__y',
      'y_M_lllllllV_y',
      'y___llv_Hllll_',
      'yyyyyyyyayyyyy',
    ],
    doors: {
      42: { to: 'magma_caverns', spawn: 96, name: 'Back to the Magma Caverns', style: 'arch' },
      55: { to: 'dragons_forge', name: "The Dragon's Forge", style: 'arch' },
    },
    signs: { 17: 'The braziers cool fast in this wind. Light both before the first goes out!' },
    props: [['volcano_vent', 110, 60], ['forge', 192, 60], ['volcano_vent', 274, 60], ['volcano_vent', 72, 150], ['volcano_vent', 312, 150]],
  },
  dragons_forge: {
    title: "Dragon's Forge", biome: 'volcanic', music: 'battle', region: 'Sky Realms', pos: [346, 40], boss: true,
    map: [
      'yylllll___llly',
      'y_l________l_y',
      'l___vV___Vv__l',
      'dF_____Q_____l',
      'l____________l',
      'l__vV_____Vv_l',
      'y_l____H___lay',
      'yyllll___lllyy',
    ],
    doors: { 42: { to: 'lava_bridges', spawn: 55, name: 'Back to the Lava Bridges', style: 'arch' } },
    props: [['volcano_vent', 110, 60], ['forge', 192, 60], ['volcano_vent', 276, 60], ['volcano_vent', 72, 150], ['volcano_vent', 312, 150]],
  },
  whispering_woods: {
    title: 'Whispering Woods', biome: 'enchanted', music: 'forest', region: 'Sky Realms', pos: [196, 12],
    map: [
      'TToo_TTT__ToTT',
      'T_o___T__J_oaT',
      '__e_N___T__e_T',
      'dF__T__UT_____',
      '___eTT____T_R_',
      'T_3__T___TT_CT',
      'TT__N__J____d_',
      'TTToo_____oo_T',
    ],
    doors: {
      42: { to: 'elemental_portal', spawn: 91, name: 'Back to the Nexus', style: 'portal' },
      96: { to: 'fairy_glade', name: 'Into the Fairy Glade', style: 'hole' },
    },
    props: [['tree_magic', 100, 60], ['shroom_big', 150, 60], ['tree_magic', 220, 60], ['shroom_big', 290, 60], ['tree_magic', 72, 120], ['shroom_big', 312, 90]],
  },
  fairy_glade: {
    title: 'Fairy Glade', biome: 'enchanted', music: 'forest', region: 'Sky Realms', pos: [232, 12],
    map: [
      'TTTTTTTTTTTTTT',
      'T_ooo_T_oo_&_T',
      'T_TTo_To_T___T',
      'd_ooo_Uoo_eoo?',
      'T_TToTToTTTToT',
      'Too_oRooo_Joo_',
      'T&T_ToooTTNoad',
      'TTTTTTTTTTTTTT',
    ],
    doors: {
      42: { to: 'whispering_woods', spawn: 96, name: 'Back to the Whispering Woods', style: 'hole' },
      97: { to: 'world_tree', name: 'The World Tree', style: 'hole' },
    },
    npcs: { 25: 'queen', 85: 'kit5' },
    signs: { 55: 'The fog here plays tricks. Treants hide among the trees.' },
    props: [['tree_magic', 100, 60], ['shroom_big', 160, 60], ['tree_magic', 230, 60], ['shroom_big', 290, 60], ['shroom_big', 72, 120], ['tree_magic', 312, 90]],
  },
  world_tree: {
    title: 'The World Tree', biome: 'enchanted', music: 'battle', region: 'Sky Realms', pos: [268, 12], boss: true,
    map: [
      'TTee_______eTT',
      'T_e__J___J_e_T',
      'e___U_____U__e',
      'dF_____t_____e',
      'e____________e',
      'e__R_______R_e',
      'T_e____H___eaT',
      'TTee___4___eTT',
    ],
    doors: { 42: { to: 'fairy_glade', spawn: 97, name: 'Back to the Fairy Glade', style: 'hole' } },
    props: [['shroom_big', 110, 60], ['tree_magic', 192, 60], ['shroom_big', 274, 60], ['shroom_big', 72, 140], ['shroom_big', 312, 140]],
    backdrop: [['worldtree', 352, 214], ['worldtree', 30, 222]],
  },
  // ───────────── Act IV: The Void ─────────────
  dreamspace: {
    title: 'Dreamspace', biome: 'dream', music: 'dream', region: 'The Void', pos: [118, 190], crumbleTo: '~',
    map: [
      '~~~~~~~~~~~~~~',
      '~_?~~_U_____a~',
      '~_~~~_~~_~_~_~',
      'd__uuu~~_~_~_~',
      '~_~~~_~U__~_~~',
      '~_?~~_~~~_~_~~',
      '~__z__==__U__d',
      '~~~~~~~~~~~~~~',
    ],
    doors: {
      42: { to: 'fox_hole', spawn: 48, name: 'Back through the rift', style: 'rift' },
      97: { to: 'the_void', name: 'Deeper into the Void', style: 'rift' },
    },
    signs: {
      16: 'A memory: Grandma, teaching a tiny fox to light his very first flame.',
      72: 'A memory: the Sky Isles, bright and high, before the Void began to pull them down.',
    },
    props: [['crystal_big', 110, 60], ['shroom_big', 192, 60], ['crystal_big', 274, 60]],
  },
  the_void: {
    title: 'The Void', biome: 'void', music: 'void', region: 'The Void', pos: [154, 190], crumbleTo: '~', reform: 6,
    map: [
      '~~~~~~~~~~~~~~',
      '~*__q~~__z__*~',
      '~_~~_~~_~~~_~~',
      'd__~_uu_~q__#d',
      '~_~~_~~_~~~_~~',
      '~_z__~~___~_~~',
      '~_~~~~~~_*__a~',
      '~~~~~~~~~~~~~~',
    ],
    doors: {
      42: { to: 'dreamspace', spawn: 97, name: 'Back to the Dreamspace', style: 'rift' },
      55: { to: 'void_heart', name: 'The heart of the Void', style: 'rift' },
    },
    props: [['crystal_big', 110, 60], ['crystal_big', 274, 60]],
  },
  void_heart: {
    title: 'Heart of the Void', biome: 'void', music: 'battle', region: 'The Void', pos: [190, 190], boss: true,
    map: [
      '~~~~~~~~~~~~~~',
      '~~__________~~',
      '~_*________*_~',
      'dF_____A_____~',
      '~____________~',
      '~_*________*_~',
      '~~____H_____~~',
      '~~~~~~~~~~~~~~',
    ],
    doors: { 42: { to: 'the_void', spawn: 55, name: 'Back into the Void', style: 'rift' } },
    props: [],
  },
};

const KITS = ['kit1', 'kit2', 'kit3', 'kit4', 'kit5'];
