// Generated by gbc/tools/music.js from "2022-09-22 Forest Exploration" (Bitwig) and gbc/music/forest.map.js. Do not edit.
'use strict';
module.exports = {
 "about": "2022-09-22 Forest Exploration: converted by gbc/tools/music.js from gbc/music/forest.map.js. Do not edit; change the map.",
 "tempo": 8,
 "bpm": 120,
 "beats": [
  0,
  340
 ],
 "duty": [
  {
   "duty": 2,
   "env": 176
  },
  {
   "duty": 1,
   "env": 128
  },
  {
   "duty": 0,
   "env": 112
  },
  {
   "duty": 2,
   "env": 162
  },
  {
   "duty": 2,
   "env": 98
  },
  {
   "duty": 1,
   "env": 147
  },
  {
   "duty": 1,
   "env": 96
  }
 ],
 "dutyNames": [
  "lead",
  "soft",
  "thin",
  "pluck",
  "pluck-soft",
  "bell",
  "pad"
 ],
 "wave": [
  {
   "wave": 0,
   "volume": 1
  },
  {
   "wave": 0,
   "volume": 2
  },
  {
   "wave": 1,
   "volume": 1
  },
  {
   "wave": 1,
   "volume": 2
  }
 ],
 "waveNames": [
  "bass",
  "bass-soft",
  "round",
  "round-soft"
 ],
 "noise": [
  {
   "env": 193
  },
  {
   "env": 162
  },
  {
   "env": 146
  },
  {
   "env": 81
  },
  {
   "env": 99
  },
  {
   "env": 113
  }
 ],
 "noiseNames": [
  "kick",
  "snare",
  "clap",
  "hat",
  "open",
  "perc"
 ],
 "drums": {
  "kick": [
   "C4",
   1
  ],
  "snare": [
   "A5",
   2
  ],
  "clap": [
   "G5",
   3
  ],
  "hat": [
   "C7",
   4
  ],
  "open": [
   "B6",
   5
  ],
  "perc": [
   "E6",
   6
  ]
 },
 "waves": [
  [
   0,
   0,
   1,
   1,
   2,
   2,
   3,
   3,
   4,
   4,
   5,
   5,
   6,
   6,
   7,
   7,
   8,
   8,
   9,
   9,
   10,
   10,
   11,
   11,
   12,
   12,
   13,
   13,
   14,
   14,
   15,
   15
  ],
  [
   0,
   3,
   6,
   8,
   11,
   12,
   14,
   15,
   15,
   15,
   14,
   12,
   11,
   8,
   6,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
  ]
 ],
 "patterns": {
  "P0": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - . . . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07"
  },
  "P1": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - . . . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - .",
   "noise": "clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07"
  },
  "P2": {
   "p1": ". . . . E5:pad . . . . . . . . . . . . . . . - . . . D#5:pad . . . . . . . . . . . A#5:pad . . . . . . . . . . . . . . . - . . . D6:pad . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "clap~f08 .~f07 hat~f08 hat~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P3": {
   "p1": ". . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C5:round . . - . . . . . . . . F5:round . . - A#4:round . . - . . . . C5:round . . - . . . . C5:round . . - . . . . . . . . F5:round . . - G#5:round . . - . . . . G5:round . . -",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P4": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - . . . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07"
  },
  "P5": {
   "p1": ". . . . C7:lead . . . . . . . . . . . F7:lead . . . D#7:lead . . . . . . . A#6:lead . . . . . . . C7:lead . . . . . . . . . . . F7:lead . . . G#7:lead . . . . . . . G7:lead . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "clap~f08 .~f07 hat~f08 hat~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P6": {
   "p1": ". . . . C7:lead . . . . . . . . . . . F7:lead . . . D#7:lead . . . . . . . A#6:lead . . . . . . . C7:lead . . . . . . . . . . . F7:lead . . . G#7:lead . . . . . . . G7:lead . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P7": {
   "p1": ". . . . C7:lead . . . . . . . . . . . F7:lead . . . D#7:lead . . . . . . . A#6:lead . . . . . . . C7:lead . . . . . . . . . . . F7:lead . . . G#7:lead . . . . . . . G7:lead . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - . . . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - .",
   "noise": "kick~f08 clap~f07 hat~f08 clap~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07"
  },
  "P8": {
   "p1": ". . . . D5:pad . . . . . . . . . . . . . . . - . . . C#5:pad . . . . . . . . . . . G#5:pad . . . . . . . . . . . . . . . - . . . C6:pad . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "clap~f08 .~f07 hat~f08 hat~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P9": {
   "p1": ". . . . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P10": {
   "p1": "C7:lead . - . C7:lead . . . . . . . . . . . F7:lead . . . D#7:lead . . . . . . . A#6:lead . . . . . . . C7:lead . . . . . . . . . . . F7:lead . . . G#7:lead . . . . . . . G7:lead . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - . . . . . C4:round - . D#4:round G4:round - C4:round - . . . . . . . . F4:round F4:round - . . . . . D#4:round D#4:round - .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 kick~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07 clap~f08 .~f07 hat~f08 hat~f07 kick~f08 kick~f07 hat~f08 hat~f07 open~f08 .~f07 hat~f08 hat~f07 kick~f08 perc~f07 hat~f08 hat~f07"
  },
  "P11": {
   "p1": ". . . . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "clap~f08 .~f07 hat~f08 hat~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P12": {
   "p1": "C7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round . . . A#4:round . . . C5:round . . . - . . . D#5:round D5:round D#5:round - . . D#5:round D#5:round - . D#5:round D#5:round F5:round . - . C5:round . . . A#5:round . . . C6:round . . . - . . . D#6:round D6:round D#6:round - . . A#5:round A#5:round - . A#5:round A#5:round",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P13": {
   "p1": "C7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": "C6:round . - . C4:round . . . A#4:round . . . C5:round . . . - . . . D#5:round D5:round D#5:round - . . D#5:round D#5:round - . D#5:round D#5:round F5:round . - . C5:round . . . A#5:round . . . C6:round . . . - . . . D#6:round D6:round D#6:round - . . A#5:round A#5:round - . A#5:round A#5:round",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P14": {
   "p1": "C7:lead . - . D5:pad . . . . . . . . . . . . . . . - . . . C#5:pad . . . . . . . . . . . G#5:pad . . . . . . . . . . . . . . . - . . . C6:pad . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": "C6:round . - . C6:round . . . . . . . . . . . F6:round . . . D#6:round . . . . . . . A#5:round . . . . . . . C6:round . . . . . . . . . . . F6:round . . . G#6:round . . . . . . . G6:round . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P15": {
   "p1": ". . . . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C6:round . . . . . . . . . . . F6:round . . . D#6:round . . . . . . . A#5:round . . . . . . . C6:round . . . . . . . . . . . F6:round . . . G#6:round . . . . . . . G6:round . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P16": {
   "p1": "C7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C5:round . . . . . . . . . . . F5:round . . . D#5:round . . . . . . . A#4:round . . . . . . . C5:round . . . . . . . . . . . F5:round . . . G#5:round . . . . . . . G5:round . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 clap~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P17": {
   "p1": "C7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C5:round . . . . . . . . . . . F5:round . . . D#5:round . . . . . . . A#4:round . . . . . . . C5:round . . . . . . . . . . . F5:round . . . G#5:round . . . . . . . G5:round . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P18": {
   "p1": "C7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . D#7:lead D#7:lead - . D#7:lead D#7:lead F7:lead . - . C6:lead . . . A#6:lead . . . C7:lead . . . - . . . D#7:lead D7:lead D#7:lead - . . A#6:lead A#6:lead - . A#6:lead A#6:lead",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C4:round . . . . . . . . . . . F4:round . . . D#4:round . . . . . . . A#3:round . . . . . . . C4:round . . . . . . . . . . . F4:round . . . G#4:round . . . . . . . G4:round . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P19": {
   "p1": "C7:lead . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C6:round . . - . . . . . . . . F6:round . . - A#5:round . . - . . . . C6:round . . - . . . . C6:round . . - . . . . . . . . F6:round . . - G#6:round . . - . . . . G6:round . . -",
   "noise": ".~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P20": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . F5:soft . F5:soft . F5:soft . F5:soft . D#5:soft . D#5:soft . D#5:soft . D#5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . C5:soft . A#4:soft . A#4:soft . A#4:soft . A#4:soft . D#5:soft . D#5:soft .",
   "wave": ". . . . C6:round . . - . . . . . . . . F6:round . . - A#5:round . . - . . . . C6:round . . - . . . . C6:round . . - . . . . . . . . F6:round . . - G#6:round . . - . . . . G6:round . . -",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P21": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#5:soft . D#5:soft . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  }
 },
 "order": [
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "P13",
  "P14",
  "P15",
  "P16",
  "P17",
  "P18",
  "P19",
  "P20",
  "P21"
 ]
};
