// Generated by gbc/tools/music.js from "2022-10-30 Forest Home" (Bitwig) and gbc/music/home.map.js. Do not edit.
'use strict';
module.exports = {
 "about": "2022-10-30 Forest Home: converted by gbc/tools/music.js from gbc/music/home.map.js. Do not edit; change the map.",
 "tempo": 8,
 "bpm": 120,
 "beats": [
  0,
  412
 ],
 "duty": [
  {
   "duty": 2,
   "env": 176
  },
  {
   "duty": 1,
   "env": 128
  },
  {
   "duty": 0,
   "env": 112
  },
  {
   "duty": 2,
   "env": 162
  },
  {
   "duty": 2,
   "env": 98
  },
  {
   "duty": 1,
   "env": 147
  },
  {
   "duty": 1,
   "env": 96
  }
 ],
 "dutyNames": [
  "lead",
  "soft",
  "thin",
  "pluck",
  "pluck-soft",
  "bell",
  "pad"
 ],
 "wave": [
  {
   "wave": 0,
   "volume": 1
  },
  {
   "wave": 0,
   "volume": 2
  },
  {
   "wave": 1,
   "volume": 1
  },
  {
   "wave": 1,
   "volume": 2
  }
 ],
 "waveNames": [
  "bass",
  "bass-soft",
  "round",
  "round-soft"
 ],
 "noise": [
  {
   "env": 193
  },
  {
   "env": 162
  },
  {
   "env": 146
  },
  {
   "env": 81
  },
  {
   "env": 99
  },
  {
   "env": 113
  }
 ],
 "noiseNames": [
  "kick",
  "snare",
  "clap",
  "hat",
  "open",
  "perc"
 ],
 "drums": {
  "kick": [
   "C4",
   1
  ],
  "snare": [
   "A5",
   2
  ],
  "clap": [
   "G5",
   3
  ],
  "hat": [
   "C7",
   4
  ],
  "open": [
   "B6",
   5
  ],
  "perc": [
   "E6",
   6
  ]
 },
 "waves": [
  [
   0,
   0,
   1,
   1,
   2,
   2,
   3,
   3,
   4,
   4,
   5,
   5,
   6,
   6,
   7,
   7,
   8,
   8,
   9,
   9,
   10,
   10,
   11,
   11,
   12,
   12,
   13,
   13,
   14,
   14,
   15,
   15
  ],
  [
   0,
   3,
   6,
   8,
   11,
   12,
   14,
   15,
   15,
   15,
   14,
   12,
   11,
   8,
   6,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
  ]
 ],
 "patterns": {
  "P0": {
   "p1": ". . . . C#3:lead - . . . . . . F#3:lead - . . . . . . F#3:lead - A3:lead - G#3:lead - B3:lead - F3:lead - . . . . . . C#3:lead - . . . . . . F#3:lead - . . . . . . F#3:lead - A3:lead - G#3:lead - B3:lead - F3:lead - . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P1": {
   "p1": ". . . . . . . . . . . . . . . . . . . . C#4:lead - . . . . . . F#3:lead - . . . . . . F#4:lead - A4:lead - G#4:lead - B4:lead - F4:lead - . . . . . . F#4:lead . A4:lead . . . F#4:lead . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . F#4:bass . A4:bass . . . F#4:bass . . . . . F4:bass . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . F#4:bass . A4:bass . . . F#4:bass . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P2": {
   "p1": "F4:lead . . . C#3:lead - . . . . . . F#3:lead - . . . . . . F#3:lead - A3:lead - G#3:lead - B3:lead - F3:lead - . . . . . . F#5:lead A5:lead G#5:lead B5:lead F5:lead - . . F#5:lead C#6:lead A5:lead B5:lead C#6:lead - . . F#5:lead F#5:lead A5:lead F#5:lead F5:lead - . . F#5:lead F#5:lead C#6:lead F#5:lead",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "F4:bass . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P3": {
   "p1": "F5:lead - . . D6:lead B5:lead G#5:lead D6:lead B5:lead C#6:lead D6:lead C#6:lead B5:lead - G#5:lead - F#5:lead - F#5:lead - . . . . F#5:lead F#5:lead F#5:lead F#5:lead A5:lead A5:lead A5:lead A5:lead C#6:lead C#6:lead C#6:lead C#6:lead D6:lead D6:lead B5:lead B5:lead F5:lead F5:lead F5:lead F5:lead G#5:lead G#5:lead G#5:lead G#5:lead C#6:lead C#6:lead C#6:lead C#6:lead F#6:lead F#6:lead F6:lead F6:lead F#5:lead F#5:lead F#5:lead F#5:lead A5:lead A5:lead A5:lead A5:lead",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . F#5:bass F#4:bass F#5:bass F#4:bass A5:bass A4:bass A5:bass A4:bass",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P4": {
   "p1": "C#6:lead C#6:lead C#6:lead C#6:lead D6:lead D6:lead B5:lead B5:lead F5:lead F5:lead F5:lead F5:lead G#5:lead G#5:lead G#5:lead G#5:lead C#6:lead C#6:lead C#6:lead C#6:lead F#6:lead F#6:lead F6:lead F6:lead - . . . F#6:lead F#6:lead A6:lead F#6:lead F6:lead - . . F#6:lead F#6:lead C#7:lead F#6:lead F6:lead - . . D7:lead B6:lead G#6:lead D7:lead B6:lead C#7:lead D7:lead C#7:lead B6:lead - G#6:lead - F#6:lead - F#6:lead - F#5:lead F#5:lead F#5:lead F#5:lead",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "C#6:bass C#5:bass C#6:bass C#5:bass D6:bass D6:bass B5:bass B5:bass F5:bass F5:bass F5:bass F5:bass G#5:bass G#5:bass G#5:bass G#5:bass C#6:bass C#6:bass C#6:bass C#6:bass F#6:bass F#6:bass F6:bass F6:bass - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P5": {
   "p1": "A5:lead A5:lead A5:lead A5:lead C#6:lead C#6:lead C#6:lead C#6:lead D6:lead D6:lead B5:lead B5:lead F5:lead F5:lead F5:lead F5:lead G#5:lead G#5:lead G#5:lead G#5:lead C#6:lead C#6:lead C#6:lead C#6:lead F#6:lead F#6:lead F6:lead F6:lead F#5:lead F#5:lead F#5:lead F#5:lead A5:lead A5:lead A5:lead A5:lead C#6:lead C#6:lead C#6:lead C#6:lead D6:lead D6:lead B5:lead B5:lead F5:lead F5:lead F5:lead F5:lead G#5:lead G#5:lead G#5:lead G#5:lead C#6:lead C#6:lead C#6:lead C#6:lead F#6:lead F#6:lead F6:lead F6:lead - . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . F#4:bass - F#4:bass - A4:bass - A4:bass - C#5:bass - C#5:bass - D5:bass - B4:bass - F4:bass - F4:bass - G#4:bass - G#4:bass - C#5:bass - C#5:bass - F#5:bass - F5:bass - . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P6": {
   "p1": "F#6:lead F#6:lead A6:lead F#6:lead F6:lead - . . F#6:lead F#6:lead C#7:lead F#6:lead F6:lead - . . D7:lead B6:lead G#6:lead D7:lead B6:lead C#7:lead D7:lead C#7:lead B6:lead - G#6:lead - F#6:lead - F#6:lead - . . . . . . . . . . . . . . . . . . . . F#6:lead F#6:lead A6:lead F#6:lead F6:lead - . . F#6:lead F#6:lead C#7:lead F#6:lead",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "F#4:bass . . . A4:bass . . . C#4:bass . . . F4:bass . . . F#4:bass . . . A4:bass . . . F#4:bass . . . F4:bass . . . - . . . F#4:round F#5:round F#4:round F#5:round A4:round A5:round A4:round A5:round C#4:round C#5:round C#4:round C#5:round F4:round F5:round F4:round F5:round F#4:round F#5:round F#4:round F#5:round A4:round A5:round A4:round A5:round C#5:round C#6:round C#5:round C#6:round",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P7": {
   "p1": "F6:lead - . . D7:lead B6:lead G#6:lead D7:lead B6:lead C#7:lead D7:lead C#7:lead B6:lead - G#6:lead - F#6:lead - F#6:lead - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . C#5:lead C#6:lead C#5:lead C#6:lead D5:lead D6:lead B4:lead B5:lead F4:lead F5:lead F4:lead F5:lead",
   "p2": ". . . . . . . . . . . . . . . . . . . . F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft",
   "wave": "F4:round F5:round F4:round F5:round - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P8": {
   "p1": "G#4:lead G#5:lead G#4:lead G#5:lead C#5:lead C#6:lead C#5:lead C#6:lead F#5:lead F#6:lead F5:lead F6:lead - . . . . . . . A6:lead . . . A4:lead A5:lead F#7:lead . . . D7:lead . . . F4:lead F5:lead C#7:lead . . . . . . . C#5:lead C#6:lead C#5:lead C#6:lead F4:lead F5:lead F4:lead F5:lead D7:lead . . . - . F#7:lead . . . D7:lead .",
   "p2": "D5:soft D6:soft D5:soft D6:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P9": {
   "p1": ". . - . F7:lead . . . . . . . - . . . . . . . A6:lead . . . C#6:lead - F#7:lead . . . D7:lead . . . - . C#7:lead . . . . . . . - . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead .",
   "p2": "D5:soft D6:soft D5:soft D6:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P10": {
   "p1": ". . - . F7:lead . . . . . . . - . . . . . . . F#6:lead F#6:lead A6:lead F#6:lead F6:lead - . . F#6:lead F#6:lead C#7:lead F#6:lead F6:lead - . . D7:lead B6:lead G#6:lead D7:lead B6:lead C#7:lead D7:lead C#7:lead B6:lead - G#6:lead - F#6:lead - F#6:lead - F#6:lead F#6:lead A6:lead F#6:lead F6:lead - . . F#6:lead F#6:lead C#7:lead F#6:lead",
   "p2": "D5:soft D6:soft D5:soft D6:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . F#4:bass . . . A4:bass . . . C#4:bass . . . F4:bass . . . F#4:bass . . . A4:bass . . . F#4:bass . . . F4:bass . . . F#4:bass . . . A4:bass . . . C#4:bass . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P11": {
   "p1": "F6:lead - . . D7:lead B6:lead G#6:lead D7:lead B6:lead C#7:lead D7:lead C#7:lead B6:lead - G#6:lead - F#6:lead - F#6:lead - A6:lead . . . C#6:lead - F#7:lead . . . D7:lead . . . - . C#7:lead . . . . . . . - . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft",
   "wave": "F4:bass . . . F#4:bass . . . A4:bass . . . F#4:bass . . . F4:bass . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P12": {
   "p1": ". . - . F7:lead . . . . . . . - . . . . . . . A6:lead . . . C#6:lead - F#7:lead . . . D7:lead . . . - . C#7:lead . . . . . . . - . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead .",
   "p2": "D5:soft D6:soft D5:soft D6:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F#4:soft F#5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft C#5:soft C#6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft D5:soft D6:soft",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P13": {
   "p1": ". . - . F7:lead . . . . . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D5:soft D6:soft D5:soft D6:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft F4:soft F5:soft - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . F#4:round . F#5:round . A4:round . A5:round . C#4:round . C#5:round . F4:round . F5:round . F#4:round . F#5:round . A4:round . A5:round . C#5:round . C#6:round . F4:round . F5:round . F#4:bass . . . A4:bass . . . C#4:bass . . .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P14": {
   "p1": ". . . . . . . . . . . . . . . . . . . . F#7:lead F#7:lead A7:lead F#7:lead F7:lead - . . F#7:lead F#7:lead C#8:lead F#7:lead F7:lead - . . D8:lead B7:lead G#7:lead D8:lead B7:lead C#8:lead D8:lead C#8:lead B7:lead - G#7:lead - F#7:lead - F#7:lead - A6:lead . . . C#6:lead - F#7:lead . . . D7:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . F#4:soft - F#4:soft - F#4:soft - F#4:soft - F#4:soft - F#4:soft -",
   "wave": "F4:bass . . . F#4:bass . . . A4:bass . . . F#4:bass . . . F4:bass . . . F#4:bass . . . A4:bass . . . C#4:bass . . . F4:bass . . . F#4:bass . . . A4:bass . . . F#4:bass . . . F4:bass . . . - . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P15": {
   "p1": ". . - . C#7:lead . . . C#6:lead - . . . . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead . . . - . F7:lead . . . F5:lead - . . . . . . . . . . A6:lead . . . C#6:lead - F#7:lead . . . D7:lead .",
   "p2": "F#4:soft - F#4:soft - F4:soft - F4:soft - F4:soft - F4:soft - C#5:soft - C#5:soft - C#5:soft - C#5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F#4:soft - F#4:soft - F#4:soft - F#4:soft - F#4:soft - F#4:soft -",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P16": {
   "p1": ". . - . C#7:lead . . . C#6:lead - . . . . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead . . . - . F7:lead . . . F5:lead - . . . . . . . . . . A6:lead . . . C#6:lead - F#7:lead . . . D7:lead .",
   "p2": "F#4:soft - F#4:soft - F4:soft - F4:soft - F4:soft - F4:soft - C#5:soft - C#5:soft - C#5:soft - C#5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - D5:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F4:soft - F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P17": {
   "p1": ". . - . C#7:lead . . . C#6:lead - . . . . . . . . . . D7:lead . . . F#5:lead - F#7:lead . . . D7:lead . . . - . F7:lead . . . F5:lead - . . . . . . . . . . A7:lead . G#7:lead . F7:lead . F#7:lead . . . D7:lead .",
   "p2": "F#4:soft . F#4:soft . F4:soft . F4:soft . F4:soft . F4:soft . C#5:soft . C#5:soft . C#5:soft . C#5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P18": {
   "p1": ". . - . C#7:lead . . . C#6:lead - . . . . . . . . . . A7:lead . G#7:lead . F7:lead . F#7:lead . . . D7:lead . . . - . F7:lead . . . F5:lead - . . . . . . . . . . A7:lead - G#7:lead - F7:lead - F#7:lead . . . D7:lead .",
   "p2": "F#4:soft . F#4:soft . F4:soft . F4:soft . F4:soft . F4:soft . C#5:soft . C#5:soft . C#5:soft . C#5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P19": {
   "p1": ". . - . C#7:lead . . . C#6:lead - . . . . . . . . . . A7:lead - G#7:lead - F7:lead - F#7:lead . . . D7:lead . . . - . F7:lead . . . G#7:lead . . . C#8:lead D8:lead F#8:lead D8:lead F8:lead . . . F#8:lead - F#8:lead - A8:lead - G#8:lead - F#8:lead - C#8:lead .",
   "p2": "F#4:soft . F#4:soft . F4:soft . F4:soft . F4:soft . F4:soft . C#5:soft . C#5:soft . C#5:soft . C#5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft . F#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P20": {
   "p1": "- . D8:lead . C#8:lead . . . . . . . - . . . . . . . F#8:lead - F#8:lead - A8:lead - G#8:lead - F#8:lead - C#8:lead . - . F#8:lead . F8:lead . . . . . . . - . . . . . . . . . . . . . . . . . . .",
   "p2": "F#4:soft . F#4:soft . F4:soft . F4:soft . F4:soft . F4:soft . C#5:soft . C#5:soft . C#5:soft . C#5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . D5:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . F4:soft . - . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . F#4:round . F#5:round . A4:round . A5:round . C#4:round . C#5:round .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07"
  },
  "P21": {
   "p1": ". . . . . . . . . . . . . . . . . . . . F#7:lead - F#7:lead - A7:lead - G#7:lead - F#7:lead - C#7:lead . - . D7:lead . C#7:lead . . . . . . . - . . . . . . . F#7:lead - F#7:lead - A7:lead - G#7:lead - F#7:lead - C#7:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . F#7:bell - F#7:bell - A7:bell - G#7:bell - F#7:bell - C#7:bell . F#4:soft . D7:bell . C#7:bell . . . . . . . C#5:soft . C#5:soft . C#5:soft . C#5:soft . F#8:bell - F#8:bell - A8:bell - G#8:bell - F#8:bell - C#8:bell .",
   "wave": "F4:round . F5:round . F#4:round . F#5:round . A4:round . A5:round . C#5:round . C#6:round . F4:round . F5:round . F#3:bass . F#3:bass . F#3:bass . F#3:bass . A3:bass . A3:bass . A3:bass . A3:bass . F3:bass . F3:bass . F3:bass . F3:bass . C#4:bass . C#4:bass . C#4:bass . C#4:bass . D3:bass . D3:bass . D3:bass . D3:bass . A3:bass . A3:bass .",
   "noise": "kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 kick~f08 .~f07 kick~f08 .~f07 kick~f08 kick~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P22": {
   "p1": "- . F#7:lead . F7:lead . . . . . . . - . . . . . . . F#7:lead - F#7:lead - A7:lead - G#7:lead - F#7:lead - C#7:lead . - . D7:lead . C#7:lead . . . . . . . - . . . . . . . F#7:lead - F#7:lead - A7:lead - G#7:lead - F#7:lead - C#7:lead .",
   "p2": "D5:soft . F#8:bell . F8:bell . . . . . . . F4:soft . F4:soft . F4:soft . F4:soft . F#7:bell - F#7:bell - A7:bell - G#7:bell - F#7:bell - C#7:bell . F#4:soft . D7:bell . C#7:bell . . . . . . . C#5:soft . C#5:soft . C#5:soft . C#5:soft . F#8:bell - F#8:bell - A8:bell - G#8:bell - F#8:bell - C#8:bell .",
   "wave": "A3:bass . A3:bass . F3:bass . F3:bass . F3:bass . F3:bass . C#4:bass . C#4:bass . C#4:bass . C#4:bass . F#3:bass . F#3:bass . F#3:bass . F#3:bass . A3:bass . A3:bass . A3:bass . A3:bass . F3:bass . F3:bass . F3:bass . F3:bass . C#4:bass . C#4:bass . C#4:bass . C#4:bass . D3:bass . D3:bass . D3:bass . D3:bass . A3:bass . A3:bass .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P23": {
   "p1": "- . F#7:lead . F7:lead . . . . . . . - . . . . . . . A7:lead . G#7:lead . F7:lead . F#7:lead . . . D7:lead . . . - . C#7:lead . . . . . . . - . . . . . . . A7:lead . G#7:lead . F7:lead . F#7:lead . . . D7:lead .",
   "p2": "D5:soft . F#8:bell . F8:bell . . . . . . . F4:soft . F4:soft . F4:soft . F4:soft . A8:bell . G#8:bell . F8:bell . F#8:bell . . . D8:bell . . . F#4:soft . C#8:bell . . . . . . . C#5:soft . C#5:soft . C#5:soft . C#5:soft . A8:bell . G#8:bell . F8:bell . F#8:bell . . . D8:bell .",
   "wave": "A3:bass . A3:bass . F3:bass . F3:bass . F3:bass . F3:bass . C#4:bass . C#4:bass . C#4:bass . C#4:bass . F#4:round . F#5:round . F#4:round . F#5:round . F#4:round . F#5:round . F#4:round . F#5:round . F4:round . F5:round . F4:round . F5:round . C#5:round . C#6:round . C#5:round . C#6:round . D5:round . D6:round . D5:round . D6:round . D5:round . D6:round .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 .~f08 .~f07 kick~f08 .~f07 snare~f08 .~f07 kick~f08 .~f07 snare~f08 snare~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07"
  },
  "P24": {
   "p1": ". . - . F7:lead . . . . . . . - . . . . . . . A7:lead - G#7:lead - F7:lead - F#7:lead . . . D7:lead . . . - . C#7:lead . . . . . . . - . . . . . . . A7:lead - G#7:lead - F7:lead - F#7:lead . . . D7:lead .",
   "p2": ". . D5:soft . F8:bell . . . . . . . F4:soft . F4:soft . F4:soft . F4:soft . A8:bell - G#8:bell - F8:bell - F#8:bell . . . D8:bell . . . - . C#8:bell . . . . . . . - . . . . . . . A8:bell - G#8:bell - F8:bell - F#8:bell . . . D8:bell .",
   "wave": "D5:round . D6:round . F4:round . F5:round . F4:round . F5:round . F4:round . F5:round . F4:round . F5:round . F#4:round . F#5:round . F#4:round . F#5:round . F#4:round . F#5:round . F#4:round . F#5:round . F4:round . F5:round . F4:round . F5:round . C#5:round . C#6:round . C#5:round . C#6:round . D5:round . D6:round . D5:round . D6:round . D5:round . D6:round .",
   "noise": "kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 hat~f08 .~f07 kick~f08 .~f07 snare~f08 open~f07 kick~f08 open~f07 snare~f08 snare~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  },
  "P25": {
   "p1": ". . - . F7:lead . . . G#7:lead . . . C#8:lead D8:lead F#8:lead D8:lead F8:lead . . . - . . . . . C#8:lead . F7:lead . - . F#7:lead . . . . . . . - . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . - . F8:bell . . . G#8:bell . . . C#8:bell D8:bell F#8:bell D8:bell F8:bell . . . - . . . . . C#8:bell . F8:bell . - . F#8:bell . . . . . . . - . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "D5:round . D6:round . F4:round . F5:round . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07 .~f08 .~f07"
  }
 },
 "order": [
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "P13",
  "P14",
  "P15",
  "P16",
  "P17",
  "P18",
  "P19",
  "P20",
  "P21",
  "P22",
  "P23",
  "P24",
  "P25"
 ]
};
