// Generated by gbc/tools/music.js from "2022-09-24 Plasma Blast" (Bitwig) and gbc/music/plasma.map.js. Do not edit.
'use strict';
module.exports = {
 "about": "2022-09-24 Plasma Blast: converted by gbc/tools/music.js from gbc/music/plasma.map.js. Do not edit; change the map.",
 "tempo": 7,
 "bpm": 124,
 "beats": [
  0,
  336
 ],
 "duty": [
  {
   "duty": 2,
   "env": 176
  },
  {
   "duty": 1,
   "env": 128
  },
  {
   "duty": 0,
   "env": 112
  },
  {
   "duty": 2,
   "env": 162
  },
  {
   "duty": 2,
   "env": 98
  },
  {
   "duty": 1,
   "env": 147
  },
  {
   "duty": 1,
   "env": 96
  }
 ],
 "dutyNames": [
  "lead",
  "soft",
  "thin",
  "pluck",
  "pluck-soft",
  "bell",
  "pad"
 ],
 "wave": [
  {
   "wave": 0,
   "volume": 1
  },
  {
   "wave": 0,
   "volume": 2
  },
  {
   "wave": 1,
   "volume": 1
  },
  {
   "wave": 1,
   "volume": 2
  }
 ],
 "waveNames": [
  "bass",
  "bass-soft",
  "round",
  "round-soft"
 ],
 "noise": [
  {
   "env": 193
  },
  {
   "env": 162
  },
  {
   "env": 146
  },
  {
   "env": 81
  },
  {
   "env": 99
  },
  {
   "env": 113
  }
 ],
 "noiseNames": [
  "kick",
  "snare",
  "clap",
  "hat",
  "open",
  "perc"
 ],
 "drums": {
  "kick": [
   "C4",
   1
  ],
  "snare": [
   "A5",
   2
  ],
  "clap": [
   "G5",
   3
  ],
  "hat": [
   "C7",
   4
  ],
  "open": [
   "B6",
   5
  ],
  "perc": [
   "E6",
   6
  ]
 },
 "waves": [
  [
   0,
   0,
   1,
   1,
   2,
   2,
   3,
   3,
   4,
   4,
   5,
   5,
   6,
   6,
   7,
   7,
   8,
   8,
   9,
   9,
   10,
   10,
   11,
   11,
   12,
   12,
   13,
   13,
   14,
   14,
   15,
   15
  ],
  [
   0,
   3,
   6,
   8,
   11,
   12,
   14,
   15,
   15,
   15,
   14,
   12,
   11,
   8,
   6,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
  ]
 ],
 "patterns": {
  "P0": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . D#3:soft . . . . . . . D#3:soft . A#3:soft . . . . . . . A#3:soft . B3:soft . . . . . . . A#3:soft . D#3:soft . - . . . . . . . D#3:soft . . . . . . . D#3:soft . A#3:soft . . . . . . . A#3:soft . B3:soft .",
   "wave": ". . A#5:bass . . . . . . . - . . . . . . . . . . . . . . . D#5:bass . . . . . . . - . . . . . . . . . . . . . . . G#5:bass . . . . . . . . . . . . .",
   "noise": ".~f07 .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08"
  },
  "P1": {
   "p1": ". . . . . . A#5:lead . . . . . . . . . . . . . . . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . . . A#3:soft . D#3:soft . - . . . . . . . . . . . . . . . . . . . . . . . . . . . A#3:soft . B3:soft . B3:soft . B3:soft . B3:soft . . . A#3:soft . G#3:soft . - . . . . . . . D#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . - . . . . . . . D#4:bass . . A#4:bass . D5:bass . . D#5:bass . - . A#3:bass . B3:bass . B3:bass . B3:bass . B3:bass . . . A#3:bass . G#3:bass . - . . . . . . . . .",
   "noise": ".~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 ."
  },
  "P2": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . A#5:lead . . . . . . . . . . . . . . . - . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . . . D#5:soft . A#4:soft . . . . . . . A#3:soft . B4:soft . . . . . . . A#4:soft . D#4:soft . - . . . . . . . . . . . . . . . D#3:soft . . A#3:soft . D4:soft . . D#4:soft . - . A#3:soft . B3:soft . B3:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . D#4:bass . . A#4:bass . D5:bass . . D#5:bass . - . A#3:bass . B3:bass . B3:bass .",
   "noise": ". .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08"
  },
  "P3": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "B3:soft . B3:soft . . . A#3:soft . G#3:soft . - . . . . . . . D#3:soft . . . . . . . D#3:soft . A#3:soft . . . . . . . A#3:soft . B3:soft . . . . . . . A#3:soft . D#3:soft . - . . . . . . . D#3:soft . . . . .",
   "wave": "B3:bass . B3:bass . . . A#3:bass . G#3:bass . - . . . . . . . D#4:bass . . . . . . . D#4:bass . A#4:bass . . . . . . . A#4:bass . B4:bass . . . . . . . A#4:bass . D#4:bass . - . . . . . . . D#4:bass . . . . .",
   "noise": ".~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 kick~f07 . . .~f08 .~f07 kick"
  },
  "P4": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . D#3:soft . A#3:soft . . . . . . . A#3:soft . B3:soft . . . . . . . A#3:soft . D#3:soft . - . . . . . . . D#4:soft - A#4:soft . . D#4:soft . . D#4:soft . F4:soft . . . . F4:soft . - F4:soft . F#4:soft . . . . . B4:soft . G#4:soft -",
   "wave": ". . D#4:bass . A#4:bass . . . . . . . A#4:bass . B4:bass . . . . . . . A#4:bass . D#4:bass . - . . . . . . . D#4:bass . . . . . . D#4:bass . . A#4:bass . . . . . . A#4:bass . . B4:bass . . . . . . . A#4:bass .",
   "noise": ". .~f08 .~f07 . kick .~f08 .~f07 . . kick~f08 .~f07 . . .~f08 kick~f07 . . .~f08 .~f07 kick . .~f08 .~f07 . kick~f08 .~f07 . . .~f08 kick~f07 . . .~f08 .~f07 kick . .~f08 .~f07 . kick .~f08 .~f07 . . kick~f08 .~f07 . . .~f08 kick~f07 . . .~f08 .~f07 kick .~f08 .~f07 . . kick~f08 .~f07 . . .~f08"
  },
  "P5": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "D#4:soft . . . - . . . . . D#4:soft - D#4:soft - D#4:soft . . - D#4:soft - F4:soft . . . . . F4:soft . F4:soft - F#4:soft . . . . . F#4:soft - F#4:soft - D#4:soft . . - . . . . . . . . . . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft .",
   "wave": "D#4:bass . - . . C4:bass . . . . D#4:bass . . . . . . D#4:bass . . A#4:bass . . . . . . A#4:bass . . B4:bass . . . . . . . A#4:bass . D#4:bass . D#4:bass . D4:bass C4:bass . D4:bass . - C4:bass . - C4:bass D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass .",
   "noise": "kick~f07 . . .~f08 .~f07 kick . .~f08 .~f07 . kick .~f08 .~f07 . . kick~f08 .~f07 . . .~f08 kick~f07 . .~f08 .~f07 . kick .~f08 .~f07 . . kick~f08 .~f07 . . .~f08 kick~f07 . . .~f08 .~f07 kick . .~f08 .~f07 . kick .~f08 .~f07 . . .~f08 .~f07 . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 ."
  },
  "P6": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . - . D#7:lead . A#6:lead .",
   "p2": "- . A#3:soft . A#3:soft . A#3:soft . A#3:soft . A#3:soft . - . B3:soft . B3:soft . B3:soft . B3:soft . A#3:soft . - . D#3:soft . - . . . . . . . . . . . . . . . . . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . - . A#3:soft . A#3:soft . A#3:soft .",
   "wave": "- . A#4:bass . A#4:bass . A#4:bass . A#4:bass . A#4:bass . C4:bass . B4:bass . B4:bass . B4:bass . B4:bass . A#4:bass . - . D#4:bass . - . C4:bass . - D#4:bass D4:bass C4:bass . D4:bass - . C4:bass . - D#4:bass D4:bass C4:bass D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . - D4:bass A#4:bass . A#4:bass . A#4:bass .",
   "noise": ". .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . hat~f08 .~f07 kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08"
  },
  "P7": {
   "p1": "F#6:lead . D#6:lead . - . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . . . . . . . . . . . . . . . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . - . D#7:lead . A#6:lead . F#6:lead . D#6:lead . - . B6:lead .",
   "p2": "A#3:soft . A#3:soft . - . B3:soft . B3:soft . B3:soft . B3:soft . A#3:soft . - . D#3:soft . - . . . . . . . . . . . . . . . . . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . - . A#3:soft . A#3:soft . A#3:soft . A#3:soft . A#3:soft . - . B3:soft .",
   "wave": "A#4:bass . A#4:bass . - . B4:bass . B4:bass . B4:bass . B4:bass . A#4:bass . C4:bass . D#4:bass . C4:bass . C4:bass . C4:bass . C4:bass . C4:bass . C4:bass . C4:bass . C4:bass . C4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . C4:bass . A#4:bass . A#4:bass . A#4:bass . A#4:bass . A#4:bass . C4:bass . B4:bass .",
   "noise": "hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 ."
  },
  "P8": {
   "p1": "A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . . . . . . . . . . . . . . . . . D#5:lead . . . . . D#6:lead . A#5:lead . D#5:lead . A#5:lead . . . B5:lead . . . . . - . B5:lead - B5:lead - B5:lead - B5:lead - G#5:lead .",
   "p2": "B3:soft . B3:soft . B3:soft . A#3:soft . - . D#3:soft . - . . . . . . . . . . . . . . . . . D#5:pad . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "B4:bass . B4:bass . B4:bass . A#4:bass . - D4:bass D#4:bass . - . C4:bass . C4:bass . - D4:bass C4:bass C#4:bass . - . . . . . . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass .",
   "noise": ". .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . . .~f08 kick~f07 . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08"
  },
  "P9": {
   "p1": ". . F#5:lead . . . . . . . . . . . D#5:lead . . . - . . . D#5:lead . . . . . D#6:lead . A#5:lead . D#5:lead . A#5:lead . . . B5:lead . . . . . - . B5:lead - B5:lead - B5:lead - B5:lead - G#5:lead . . . F#5:lead . . . . .",
   "p2": ". . . . . . - . . . . . . . . . . . . . . . D#5:pad . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . - .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass .",
   "noise": ".~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 ."
  },
  "P10": {
   "p1": ". . . . . . F5:lead . . . - . . . D#5:lead . . . . . D#6:lead . A#5:lead . D#5:lead . A#5:lead . . . B5:lead . . . . . - . B5:lead - B5:lead - B5:lead - B5:lead - G#5:lead . . . F#5:lead . . . . . . . . . . . D#5:lead .",
   "p2": ". . . . . . . . . . . . . . D#5:pad . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . - . . . . . . . . .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . D#4:bass .",
   "noise": "hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08"
  },
  "P11": {
   "p1": ". . - . . . A#5:lead . . . . . . . . . . . . . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "D#4:bass . D#4:bass . D#4:bass . - . . . A#4:bass . . . . . D#4:bass . . . . . - . . . . . . . A#5:bass . . . . . . . D#6:bass . A#5:bass . D#6:bass . G#6:bass . - . . . . . . . . . . . . . . . . .",
   "noise": "hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 ."
  },
  "P12": {
   "p1": "F#7:lead . D#7:lead . B6:lead . A#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead . F#7:lead . D#7:lead . B6:lead . A#6:lead .",
   "p2": ". . . . . . . . . . . . . . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . D#4:soft .",
   "wave": ". . . . . . . . . . . . . . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . D#4:bass .",
   "noise": "hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08"
  },
  "P13": {
   "p1": "D#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . - . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead . F#7:lead . D#7:lead . B6:lead . A#6:lead .",
   "p2": "D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . D#4:soft .",
   "wave": "D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . D#4:bass .",
   "noise": "hat~f07 . kick .~f08 hat~f07 . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 ."
  },
  "P14": {
   "p1": "D#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . - . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead . F#7:lead . D#7:lead . B6:lead . A#6:lead .",
   "p2": "D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . D#4:soft .",
   "wave": "D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . D#4:bass .",
   "noise": "hat .~f08 kick~f07 . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08"
  },
  "P15": {
   "p1": "D#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . - . . . . . . . . . . . A#5:lead . . . . . . . B5:lead . . . . . . . - . . . . . . . . . F#6:lead . F6:lead . D#6:lead . B5:lead . A#5:lead . . . . . G#5:lead .",
   "p2": "D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . - . . . . . . . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft .",
   "wave": "D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . - . . . . . . . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass .",
   "noise": "hat~f07 . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 ."
  },
  "P16": {
   "p1": ". . . . . . D#5:lead . . . . . . . - . . . . . . . D#5:lead . F#5:lead . A#5:lead . D#5:lead . F#5:lead . B5:lead . D#5:lead . F#5:lead . D#6:lead . - . F#6:lead . F6:lead . B5:lead . A#5:lead . F#5:lead . D#5:lead . B5:lead . A#5:lead . D#5:lead . - . D#6:lead .",
   "p2": "G#3:soft . G#3:soft . G#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass .",
   "noise": ".~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 kick . .~f08 .~f07 kick . .~f08 .~f07 kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick .~f08 .~f07 . kick~f08 .~f07"
  },
  "P17": {
   "p1": "F#6:lead . D#6:lead . B5:lead . A#5:lead . D#5:lead . D#5:lead . - . D#5:lead . D#5:lead . - . . . D#5:lead . F#5:lead . A#5:lead . D#5:lead . F#5:lead . B5:lead . D#5:lead . F#5:lead . D#6:lead . - . F#6:lead . F6:lead . B5:lead . A#5:lead . F#5:lead . D#5:lead . B5:lead . A#5:lead . D#5:lead . - . D#6:lead .",
   "p2": "G#3:soft . G#3:soft . G#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . B3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft . G#3:soft .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ". . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 . . kick~f08 .~f07 hat . kick~f08 .~f07 hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat~f08 .~f07 kick ."
  },
  "P18": {
   "p1": "F#6:lead . D#6:lead . B5:lead . F#6:lead . D#6:lead . A#6:lead . - . A#6:lead . A#6:lead . - . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead .",
   "p2": "G#3:soft . G#3:soft . G#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#3:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass .",
   "noise": "hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick .~f08 hat~f07 . kick~f08 .~f07 hat . kick~f08 .~f07"
  },
  "P19": {
   "p1": "F#7:lead . D#7:lead . B6:lead . A#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . - . . . D#6:lead . F#6:lead . A#6:lead . D#6:lead . F#6:lead . B6:lead . D#6:lead . F#6:lead . D#7:lead . - . F#7:lead . F7:lead . B6:lead . A#6:lead . F#6:lead . D#6:lead . B6:lead . A#6:lead . D#6:lead . - . D#7:lead .",
   "p2": "G#4:soft . G#4:soft . G#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . B4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft . G#4:soft .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . B4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass . G#4:bass .",
   "noise": "hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat . kick~f08 .~f07 hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat .~f08 kick~f07 . hat~f08 .~f07 kick . hat~f08 .~f07 kick ."
  },
  "P20": {
   "p1": "F#7:lead . D#7:lead . B6:lead . A#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . D#6:lead . - . . . . E5:lead - . . E5:lead E5:lead - E5:lead E5:lead - E5:lead E5:lead E5:lead . . - . E5:lead . . - E5:lead E5:lead - E5:lead . . . . . - . E5:lead . . . . . . . .",
   "p2": "G#4:soft . G#4:soft . G#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . D#4:soft . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "G#4:bass . G#4:bass . G#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . D#4:bass . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 kick . hat~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07 . .~f08 .~f07 . . .~f08 .~f07 . . .~f08 .~f07"
  }
 },
 "order": [
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "P13",
  "P14",
  "P15",
  "P16",
  "P17",
  "P18",
  "P19",
  "P20"
 ]
};
