// Generated by gbc/tools/music.js from "2022-09-23 Slim Monsters" (Bitwig) and gbc/music/slims.map.js. Do not edit.
'use strict';
module.exports = {
 "about": "2022-09-23 Slim Monsters: converted by gbc/tools/music.js from gbc/music/slims.map.js. Do not edit; change the map.",
 "tempo": 6,
 "bpm": 158,
 "beats": [
  0,
  400
 ],
 "duty": [
  {
   "duty": 2,
   "env": 176
  },
  {
   "duty": 1,
   "env": 128
  },
  {
   "duty": 0,
   "env": 112
  },
  {
   "duty": 2,
   "env": 162
  },
  {
   "duty": 2,
   "env": 98
  },
  {
   "duty": 1,
   "env": 147
  },
  {
   "duty": 1,
   "env": 96
  }
 ],
 "dutyNames": [
  "lead",
  "soft",
  "thin",
  "pluck",
  "pluck-soft",
  "bell",
  "pad"
 ],
 "wave": [
  {
   "wave": 0,
   "volume": 1
  },
  {
   "wave": 0,
   "volume": 2
  },
  {
   "wave": 1,
   "volume": 1
  },
  {
   "wave": 1,
   "volume": 2
  }
 ],
 "waveNames": [
  "bass",
  "bass-soft",
  "round",
  "round-soft"
 ],
 "noise": [
  {
   "env": 193
  },
  {
   "env": 162
  },
  {
   "env": 146
  },
  {
   "env": 81
  },
  {
   "env": 99
  },
  {
   "env": 113
  }
 ],
 "noiseNames": [
  "kick",
  "snare",
  "clap",
  "hat",
  "open",
  "perc"
 ],
 "drums": {
  "kick": [
   "C4",
   1
  ],
  "snare": [
   "A5",
   2
  ],
  "clap": [
   "G5",
   3
  ],
  "hat": [
   "C7",
   4
  ],
  "open": [
   "B6",
   5
  ],
  "perc": [
   "E6",
   6
  ]
 },
 "waves": [
  [
   0,
   0,
   1,
   1,
   2,
   2,
   3,
   3,
   4,
   4,
   5,
   5,
   6,
   6,
   7,
   7,
   8,
   8,
   9,
   9,
   10,
   10,
   11,
   11,
   12,
   12,
   13,
   13,
   14,
   14,
   15,
   15
  ],
  [
   0,
   3,
   6,
   8,
   11,
   12,
   14,
   15,
   15,
   15,
   14,
   12,
   11,
   8,
   6,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
  ]
 ],
 "patterns": {
  "P0": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . G#5:pad . . . . . . . . . . C6:pad . . . . A5:pad . . . . . . . . . . - . . . . G#5:pad . . . . . . . . . . C6:pad . . . . A5:pad . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . C5:bass . . - D#5:bass . . - D5:bass . . - C5:bass . . - C5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . - F5:bass . . - C5:bass . . -",
   "noise": ".~f06 .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . ."
  },
  "P1": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . G3:lead . . . . . . . . . . . - . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead .",
   "p2": "- . . . G#5:pad . . . . . . . . . . C6:pad . . . . A5:pad . . . . . . . . . . - . . . . G#5:pad . . . . . . . . . . C6:pad . . . . A5:pad . . . . . . . . . . .",
   "wave": ". . . . C5:bass . . - D#5:bass . . - D5:bass . . - F5:bass . . - G5:bass . . - D#5:bass . . - D5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . - C5:bass . . - C5:bass . . - . . . . C5:bass . . -",
   "noise": ".~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06"
  },
  "P2": {
   "p1": "C4:lead . . . - . . . . . . . C4:lead . . . . . . . . . . . - . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . D#5:lead . B4:lead . G3:lead . G3:lead . . . . . . . . . . .",
   "p2": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "D#5:bass . . - D5:bass . . - F5:bass . . - C5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . - F5:bass . . - G5:bass . . - D#5:bass . . - D5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . -",
   "noise": ". . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 ."
  },
  "P3": {
   "p1": "- . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . . . . . . . G4:lead . G4:lead . C5:lead . G4:lead . C4:lead . C4:lead . - . C4:lead . - . . . F#4:lead . F#4:lead . G#4:lead . G4:lead . C4:lead . C4:lead . - . G3:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "C5:bass . . - C5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . - F5:bass . . - C5:bass . . - . . . . C5:bass . . - D#5:bass . . - D5:bass . . - F5:bass . . - G5:bass . . - D#5:bass . . - D5:bass . . -",
   "noise": ".~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05"
  },
  "P4": {
   "p1": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": ".~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 ."
  },
  "P5": {
   "p1": ". . . . . . . . . . . . . . . . . . . . G3:lead . . . D4:lead . . . D#4:lead . . . B3:lead . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . . . . . . . C4:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass .",
   "noise": ".~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05"
  },
  "P6": {
   "p1": "F#4:lead . . . G4:lead . . . C4:lead . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . D#5:lead . B3:lead . G3:lead . G4:lead . . . D5:lead . . . D#5:lead . . . B4:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "- . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass .",
   "noise": ".~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06"
  },
  "P7": {
   "p1": "C5:lead . - . . . . . . . . . C5:lead . . . D#5:lead . . . G5:lead . . . C5:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead . C5:lead . - . D#6:lead . B5:lead . B4:lead . G4:lead . - . . . . . . . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . . . . . . . . . . . . .",
   "noise": "kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05"
  },
  "P8": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . C5:bass . C4:bass . C5:bass . C4:bass . - . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . F5:bass . F4:bass . C5:bass . C4:bass .",
   "noise": "kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06"
  },
  "P9": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . G3:lead . . . D4:lead . . . D#4:lead . . . B3:lead . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "- . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . F5:bass . F4:bass . G5:bass . G4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . - . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . C5:bass . C4:bass . C5:bass . C4:bass . - . . . C5:bass . C4:bass .",
   "noise": "kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . ."
  },
  "P10": {
   "p1": "C4:lead . - . . . . . . . . . C4:lead . . . D#4:lead . . . G4:lead . . . C4:lead . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . D#5:lead . B3:lead . G3:lead . - . . . . . . . . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft .",
   "wave": "D#5:bass . D#4:bass . D5:bass . D4:bass . F5:bass . F4:bass . C5:bass . C4:bass . - . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . F5:bass . F4:bass . G5:bass . G4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . - . . . . . . . . . . . . . . .",
   "noise": "kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06"
  },
  "P11": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "C5:soft . C5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . F5:soft . F5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . F5:soft . F5:soft . G5:soft . G5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 ."
  },
  "P12": {
   "p1": ". . . . C5:lead . C5:lead . D#5:lead . D#5:lead . D5:lead . D5:lead . C5:lead . C5:lead . C5:lead . C5:lead . - . . . C5:lead . C5:lead . D#5:lead . D#5:lead . D5:lead . D5:lead . F5:lead . F5:lead . C5:lead . C5:lead . - . . . C5:lead . C5:lead . D#5:lead . D#5:lead . D5:lead . D5:lead .",
   "p2": "- . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . C5:soft . C5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . F5:soft . F5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft .",
   "wave": ". . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . C5:bass . C4:bass . C5:bass . C4:bass . - . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . F5:bass . F4:bass . C5:bass . C4:bass . - . . . C5:bass . C4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass .",
   "noise": "kick~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05"
  },
  "P13": {
   "p1": "F5:lead . F5:lead . G5:lead . G5:lead . D#5:lead . D#5:lead . D5:lead . D5:lead . - . . . . . . . . . . . . . . . . . . . G3:lead . . . D4:lead . . . D#4:lead . . . B3:lead . . . C4:lead . . . - . . . . . . .",
   "p2": "F5:soft . F5:soft . G5:soft . G5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "F5:bass . F4:bass . G5:bass . G4:bass . D#5:bass . D#4:bass . D5:bass . D4:bass . - . . . C4:bass - C4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - C4:bass - C4:bass - C4:bass - C4:bass - . . . . C4:bass - C4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - F4:bass - F4:bass - C4:bass - C4:bass -",
   "noise": ".~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 ."
  },
  "P14": {
   "p1": ". . . . C4:lead . . . F#4:lead . . . G4:lead . . . D#4:lead . . . C4:lead . . . - . . . . . . . . . . . G3:lead . . . D4:lead . . . D#4:lead . . . B3:lead . . . C4:lead . . . F#4:lead . . . G4:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . C4:bass - C4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - F4:bass - F4:bass - G4:bass - G4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - . . . . C4:bass - C4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - C4:bass - C4:bass - C4:bass - C4:bass - . . . . C4:bass - C4:bass -",
   "noise": ".~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . .~f05 .~f06 . kick .~f05 .~f06 . .~f05 .~f06 . .~f05 kick~f06 . . .~f05 .~f06 . .~f05 .~f06 kick .~f05 .~f06 . .~f05 .~f06 . . kick~f05 .~f06 . .~f05"
  },
  "P15": {
   "p1": "D#4:lead . . . C4:lead . . . F#4:lead . . . B4:lead . . . C5:lead . . . G4:lead . . . D#4:lead . . . B3:lead . . . G3:lead . . . D4:lead . . . G4:lead . . . C4:lead . . . - . . . G4:lead . . . D5:lead . . . D#5:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "D#4:bass - D#4:bass - D4:bass - D4:bass - F4:bass - F4:bass - C4:bass - C4:bass - . . . . C4:bass - C4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - F4:bass - F4:bass - G4:bass - G4:bass - D#4:bass - D#4:bass - D4:bass - D4:bass - . . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": ".~f06 . .~f05 .~f06 kick . .~f05 .~f06 . .~f05 .~f06 . kick~f05 .~f06 . .~f05 .~f06 . . .~f05 kick~f06 . .~f05 .~f06 . .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 snare~f06 hat kick~f05 .~f06 snare hat kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06"
  },
  "P16": {
   "p1": "B4:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead . C5:lead . - . . . . . . . . . C5:lead . . . D#5:lead . . . G5:lead . . . C5:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead . C5:lead . - . D#6:lead . B5:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": "kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . .~f05"
  },
  "P17": {
   "p1": "B4:lead . G4:lead . G3:lead . . . D4:lead . . . D#4:lead . . . B3:lead . . . C5:lead . C4:lead . G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . . . . . . . . . C4:lead . . . D#4:lead . . . G4:lead . . . C4:lead . . . C5:lead . C4:lead .",
   "p2": ". . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . C4:soft . C4:soft . C4:soft . C4:soft . - . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . F4:soft . F4:soft . C4:soft . C4:soft . - . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft .",
   "wave": "- . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": "kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06"
  },
  "P18": {
   "p1": "G3:lead . G3:lead . B3:lead . B3:lead . C4:lead . - . D#5:lead . B4:lead . B3:lead . G3:lead . G4:lead . . . D5:lead . . . D#5:lead . . . B4:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead . C5:lead . - . . . . . . . . . C5:lead . . .",
   "p2": "F4:soft . F4:soft . G4:soft . G4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . - . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . C4:soft . C4:soft . C4:soft . C4:soft . - . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . F4:soft . F4:soft . C4:soft . C4:soft .",
   "wave": "F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass .",
   "noise": "kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat ."
  },
  "P19": {
   "p1": "D#5:lead . . . G5:lead . . . C5:lead . . . C6:lead . C5:lead . G4:lead . G4:lead . B4:lead . B4:lead . C5:lead . - . D#6:lead . B5:lead . B4:lead . G4:lead . - . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . C4:soft . C4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . F4:soft . F4:soft . G4:soft . G4:soft . D#4:soft . D#4:soft . D4:soft . D4:soft . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "- . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06"
  },
  "P20": {
   "p1": ". . . . G4:lead . . . D5:lead . D#5:lead . G5:lead . . . C6:lead . G5:lead . C5:lead . - . F#5:lead . . . G5:lead . . . D#5:lead . . . . . . . C6:lead . F#5:lead . B5:lead . . . C6:lead . . . D#6:lead . G5:lead . D#5:lead . C5:lead . B4:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": "kick . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick~f05 .~f06 . . kick~f05 .~f06 . .~f05 kick~f06 . .~f05 .~f06 kick . .~f05 .~f06 kick .~f05 .~f06 ."
  },
  "P21": {
   "p1": "G4:lead . . . . . . . D5:lead . G5:lead . B4:lead . . . G5:lead . . . G4:lead . . . D5:lead . D#5:lead . G5:lead . . . C6:lead . G5:lead . C5:lead . - . F#5:lead . . . G5:lead . . . D#5:lead . . . . . . . C6:lead . F#5:lead . B5:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass .",
   "noise": "kick~f05 .~f06 . .~f05 kick~f06 . . .~f05 kick~f06 . .~f05 .~f06 kick .~f05 .~f06 . kick .~f05 .~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat .~f05"
  },
  "P22": {
   "p1": "C6:lead . . . D#6:lead . G5:lead . D#5:lead . C5:lead . B4:lead . . . G4:lead . . . . . . . D5:lead . G5:lead . B4:lead . . . G5:lead . . . G4:lead . G5:lead . D5:lead . D#5:lead . G5:lead . G6:lead . C6:lead . G5:lead . C5:lead . G4:lead . F#5:lead . . . G5:lead . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": "- . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass .",
   "noise": "kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 ."
  },
  "P23": {
   "p1": ". . . . C6:lead . G5:lead . F#5:lead . F#4:lead . B5:lead . B4:lead . C6:lead . . . D#6:lead . G5:lead . D#5:lead . C5:lead . B4:lead . . . G4:lead . . . . . . . D5:lead . G5:lead . G4:lead . . . . . . . G4:lead . G5:lead . D5:lead . D#5:lead . G5:lead . G6:lead .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft .",
   "wave": "D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": "kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05"
  },
  "P24": {
   "p1": "C6:lead . G5:lead . C5:lead . G4:lead . F#5:lead . . . G5:lead . . . . . . . C6:lead . G5:lead . F#5:lead . F#4:lead . B5:lead . B4:lead . C6:lead . . . D#6:lead . G5:lead . D#5:lead . C5:lead . B4:lead . . . G4:lead . . . . . . . D5:lead . G5:lead . G4:lead . . .",
   "p2": "C5:soft . C5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . F5:soft . F5:soft . C5:soft . C5:soft . - . . . C5:soft . C5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft . F5:soft . F5:soft . G5:soft . G5:soft . D#5:soft . D#5:soft . D5:soft . D5:soft .",
   "wave": "C5:bass . C5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . C5:bass . C5:bass . - . . . C5:bass . C5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass . F5:bass . F5:bass . G5:bass . G5:bass . D#5:bass . D#5:bass . D5:bass . D5:bass .",
   "noise": "kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick .~f05 hat~f06 . kick~f05 .~f06 hat .~f05 kick~f06 . hat .~f05 kick~f06 . hat~f05 .~f06 kick .~f05 hat~f06 . kick~f05 .~f06 hat . kick~f05 .~f06 hat .~f05 kick~f06 . hat~f05 .~f06 kick . hat~f05 .~f06"
  }
 },
 "order": [
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "P13",
  "P14",
  "P15",
  "P16",
  "P17",
  "P18",
  "P19",
  "P20",
  "P21",
  "P22",
  "P23",
  "P24"
 ]
};
