// Generated by gbc/tools/music.js from "2022-08-28 Fang the Fox" (Bitwig) and gbc/music/title.map.js. Do not edit.
'use strict';
module.exports = {
 "about": "2022-08-28 Fang the Fox: converted by gbc/tools/music.js from gbc/music/title.map.js. Do not edit; change the map.",
 "tempo": 7,
 "bpm": 125,
 "beats": [
  0,
  336
 ],
 "duty": [
  {
   "duty": 2,
   "env": 176
  },
  {
   "duty": 1,
   "env": 128
  },
  {
   "duty": 0,
   "env": 112
  },
  {
   "duty": 2,
   "env": 162
  },
  {
   "duty": 2,
   "env": 98
  },
  {
   "duty": 1,
   "env": 147
  },
  {
   "duty": 1,
   "env": 96
  }
 ],
 "dutyNames": [
  "lead",
  "soft",
  "thin",
  "pluck",
  "pluck-soft",
  "bell",
  "pad"
 ],
 "wave": [
  {
   "wave": 0,
   "volume": 1
  },
  {
   "wave": 0,
   "volume": 2
  },
  {
   "wave": 1,
   "volume": 1
  },
  {
   "wave": 1,
   "volume": 2
  }
 ],
 "waveNames": [
  "bass",
  "bass-soft",
  "round",
  "round-soft"
 ],
 "noise": [
  {
   "env": 193
  },
  {
   "env": 162
  },
  {
   "env": 146
  },
  {
   "env": 81
  },
  {
   "env": 99
  },
  {
   "env": 113
  }
 ],
 "noiseNames": [
  "kick",
  "snare",
  "clap",
  "hat",
  "open",
  "perc"
 ],
 "drums": {
  "kick": [
   "C4",
   1
  ],
  "snare": [
   "A5",
   2
  ],
  "clap": [
   "G5",
   3
  ],
  "hat": [
   "C7",
   4
  ],
  "open": [
   "B6",
   5
  ],
  "perc": [
   "E6",
   6
  ]
 },
 "waves": [
  [
   0,
   0,
   1,
   1,
   2,
   2,
   3,
   3,
   4,
   4,
   5,
   5,
   6,
   6,
   7,
   7,
   8,
   8,
   9,
   9,
   10,
   10,
   11,
   11,
   12,
   12,
   13,
   13,
   14,
   14,
   15,
   15
  ],
  [
   0,
   3,
   6,
   8,
   11,
   12,
   14,
   15,
   15,
   15,
   14,
   12,
   11,
   8,
   6,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
  ]
 ],
 "patterns": {
  "P0": {
   "p1": ". . . . E4:lead - . . . . . . E5:lead - . . . . B4:lead - C5:lead - B4:lead - . . . . . . . . . . . . E4:lead - . . . . . . E5:lead - . . . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . .",
   "p2": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f07 . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07"
  },
  "P1": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . E5:pad . . . . . . . . . . . . . . . . . . . . . . . - . . . . . . . E6:pad . . . . . . . . . . . . . . . . . . . . . . . - . . .",
   "wave": ". . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": ". . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08"
  },
  "P2": {
   "p1": ". . . . E4:lead - . . . . . . E5:lead - . . . . B4:lead - C5:lead - B4:lead - . . . . . . . . . . . . E4:lead - . . . . . . E5:lead - . . . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . .",
   "p2": ". . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ".~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 kick . perc .~f08 kick~f07 . perc . kick~f08 .~f07 perc . kick .~f08 perc~f07 . kick . perc~f08 .~f07 kick . perc .~f08 kick~f07 . perc ."
  },
  "P3": {
   "p1": ". . . . E4:lead - . . . . E5:lead - G5:lead - E5:lead - . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . . . . . . G5:lead - E5:lead - . . E5:lead - G5:lead - E5:lead - . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 .~f07 perc . kick .~f08 perc~f07 . kick . perc~f08 .~f07 kick . perc .~f08 kick~f07 . perc . kick~f08 .~f07 perc . kick .~f08 perc~f07 . kick . perc~f08 .~f07 kick . perc .~f08 kick~f07 . perc . kick~f08 .~f07 perc . kick .~f08 perc~f07 . kick . perc~f08 .~f07 kick . perc .~f08 kick~f07 . perc . kick~f08 .~f07 perc ."
  },
  "P4": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . E4:soft . . . . . . . . . . . B4:soft . . . C5:soft . . . . . . . B4:soft . . . . . . . E4:soft . . . . . . . . . . . B4:soft . . . C5:soft . . . . . . . B4:soft . . .",
   "wave": ". . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick .~f08 perc~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 ."
  },
  "P5": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": ". . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ". . .~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . . . kick~f08 .~f07 . . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . .~f08 .~f07"
  },
  "P6": {
   "p1": ". . . . E5:lead - . E5:lead - . E5:lead - G5:lead - E5:lead - . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . . . . . . G5:lead - . G5:lead - . G5:lead - F#5:lead - E5:lead - . . B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell B6:bell~011 B6:bell - . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell C7:bell~033",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick . . .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 . . kick .~f08 .~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . . .~f08"
  },
  "P7": {
   "p1": ". . . . E4:lead - . E4:lead - . G4:lead - E5:lead - C5:lead - E4:lead - B4:lead - C5:lead - B4:lead - A#4:lead - B4:lead - . . . . . . . . E5:lead - . E5:lead - . G5:lead - E5:lead - C6:lead - E5:lead - B5:lead - C6:lead - B5:lead - A#5:lead - B5:lead - . . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell B6:bell~011 B6:bell - . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell C7:bell~033",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f07 . . . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 .~f07 . kick . .~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . . ."
  },
  "P8": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . E4:soft . . . . . . . . . . . B4:soft . . . C5:soft . . . . . . . B4:soft . . . . . . . E4:soft . . . . . . . . . . . B4:soft . . . C5:soft . . . . . . . B4:soft . . .",
   "wave": ". . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . ."
  },
  "P9": {
   "p1": ". . . . E5:lead E5:lead - E5:lead E5:lead - E5:lead E5:lead G5:lead G5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . . . . . . G5:lead G5:lead - G5:lead G5:lead - G5:lead G5:lead F#5:lead F#5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . .",
   "p2": ". . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": ". .~f08 .~f07 . kick . hat~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 open . hat kick~f08 .~f07 hat . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 ."
  },
  "P10": {
   "p1": ". . . . E4:lead E4:lead - E4:lead E4:lead - G4:lead G4:lead E5:lead E5:lead C5:lead C5:lead E4:lead E4:lead B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . . . . . . E5:lead E5:lead - E5:lead E5:lead - G5:lead G5:lead E5:lead E5:lead C6:lead C6:lead E5:lead E5:lead B5:lead B5:lead C6:lead C6:lead B5:lead B5:lead A#5:lead A#5:lead B5:lead B5:lead - . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick open .~f08 hat~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . . . kick~f08 .~f07 . . kick .~f08 hat~f07 . kick . hat~f08 .~f07 kick . hat .~f08 kick~f07 . hat . kick~f08 .~f07 hat . kick .~f08 hat~f07 . kick . .~f08 .~f07"
  },
  "P11": {
   "p1": ". . . . E4:lead - . . G5:lead - . . E5:lead - . . F#5:lead - B4:lead - C5:lead - B4:lead - . . . . . . . . . . . . G5:lead G5:lead - G5:lead G5:lead - G5:lead G5:lead E5:lead G5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . .",
   "p2": "- . . . . . . . . . . . . . . . . . . . . . . . . . E7:pad . . . - . . . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . kick . hat~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08"
  },
  "P12": {
   "p1": ". . . . G5:lead G5:lead - G5:lead G5:lead - G5:lead B5:lead F#5:lead F#5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . . . . . . E5:lead E5:lead - E5:lead E5:lead - G5:lead G5:lead E6:lead E6:lead C6:lead C6:lead E5:lead E5:lead B5:lead B5:lead C6:lead C6:lead B5:lead B5:lead A#5:lead A#5:lead B5:lead B5:lead - . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick~f07 open . hat kick~f08 .~f07 hat . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick open .~f08 hat~f07 kick . hat .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open ."
  },
  "P13": {
   "p1": ". . . . B5:lead B5:lead - B5:lead B5:lead - G5:lead G5:lead E5:lead E5:lead C6:lead E6:lead E5:lead E5:lead B5:lead B5:lead C6:lead C6:lead B5:lead B5:lead A#5:lead A#5:lead B5:lead B5:lead - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E5:pad . . . . . . . . . . . . . . . . . . . . . . . - . . .",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick~f08 open~f07 . hat kick .~f08 hat~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick open . hat~f08 kick~f07 . . . kick~f08 .~f07 . . kick .~f08 .~f07 . kick . .~f08 .~f07 kick . . .~f08 kick~f07 . . . kick~f08 .~f07 kick ."
  },
  "P14": {
   "p1": ". . . . E6:lead E5:lead E6:lead G5:lead E5:lead - E6:lead G5:lead E6:lead G5:lead E5:lead E5:lead E6:lead - E6:lead B4:lead C7:lead C5:lead C7:lead B4:lead B6:lead A#4:lead B6:lead B4:lead - . B6:lead - B6:lead - . . E6:lead E5:lead E6:lead G5:lead E5:lead - E6:lead B5:lead E6:lead G5:lead E5:lead B5:lead E6:lead - E6:lead B4:lead C7:lead C5:lead C7:lead B4:lead B6:lead A#4:lead B6:lead B4:lead - . E7:lead -",
   "p2": ". . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell B6:bell~011 B6:bell - . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell C7:bell~033",
   "wave": ". . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick kick~f08 kick~f07 kick kick . hat~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 open . hat kick~f08 .~f07 hat . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 ."
  },
  "P15": {
   "p1": "E7:lead - . . E6:lead B5:lead E6:lead E5:lead B5:lead - E6:lead G5:lead E6:lead E6:lead C6:lead C6:lead E6:lead E5:lead E6:lead B5:lead C7:lead C6:lead C7:lead B5:lead B6:lead A#5:lead B6:lead B5:lead - . B6:lead - B6:lead - . . E6:lead E6:lead E6:lead B5:lead E6:lead - E6:lead B5:lead E6:lead G5:lead C6:lead E6:lead E6:lead E5:lead E6:lead B5:lead C7:lead C6:lead C7:lead B5:lead B6:lead A#5:lead B6:lead B5:lead - . E7:lead -",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell B6:bell~011 B6:bell - . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . C7:bell C7:bell~033",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick open .~f08 hat~f07 kick . hat .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 open~f07 . hat kick .~f08 hat~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07"
  },
  "P16": {
   "p1": "E7:lead - . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . E4:soft . . . . . . . C7:bell B6:bell C7:bell B6:bell C7:bell B6:bell C7:bell B6:bell C5:soft . . . . . . . B4:soft . C7:bell B6:bell~011 B6:bell - . . E4:soft . . . . . . . E7:bell B6:bell E7:bell B6:bell E7:bell B6:bell E7:bell B6:bell C5:soft . . . . . . . B4:soft . C7:bell C7:bell~033",
   "wave": "- . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass - . . . E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass E5:bass-soft E5:bass E5:bass E5:bass B5:bass-soft B5:bass B5:bass B5:bass B5:bass-soft C6:bass C6:bass C6:bass C6:bass-soft C6:bass C6:bass C6:bass B5:bass-soft B5:bass B5:bass B5:bass",
   "noise": "kick open . hat~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08"
  },
  "P17": {
   "p1": ". . . . G5:lead E5:lead - G5:lead E5:lead - G5:lead G5:lead E5:lead G5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . B6:lead - G6:lead - E6:lead - G5:lead E5:lead - G5:lead E5:lead - G5:lead B5:lead F#5:lead G5:lead E5:lead B5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . B6:lead -",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass B4:bass-soft B4:bass B4:bass B4:bass B4:bass-soft C5:bass C5:bass C5:bass C5:bass-soft C5:bass C5:bass C5:bass B4:bass-soft B4:bass B4:bass B4:bass - . . . E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass B4:bass-soft B4:bass B4:bass B4:bass B4:bass-soft C5:bass C5:bass C5:bass C5:bass-soft C5:bass C5:bass C5:bass B4:bass-soft B4:bass B4:bass B4:bass",
   "noise": ".~f07 . . . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open ."
  },
  "P18": {
   "p1": "G6:lead - E6:lead - E5:lead B5:lead - E5:lead B5:lead - G5:lead G5:lead E6:lead E6:lead C6:lead C6:lead E5:lead E5:lead B5:lead B5:lead C6:lead C6:lead B5:lead B5:lead A#5:lead A#5:lead B5:lead B5:lead - . B6:lead - G6:lead - E6:lead - B5:lead E6:lead - B5:lead E6:lead - G5:lead B5:lead E5:lead G5:lead C6:lead E6:lead E5:lead E5:lead B5:lead B5:lead C6:lead C6:lead B5:lead B5:lead A#5:lead A#5:lead B5:lead B5:lead - . B6:lead -",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass B4:bass-soft B4:bass B4:bass B4:bass B4:bass-soft C5:bass C5:bass C5:bass C5:bass-soft C5:bass C5:bass C5:bass B4:bass-soft B4:bass B4:bass B4:bass - . . . E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass E4:bass-soft E4:bass E4:bass E4:bass B4:bass-soft B4:bass B4:bass B4:bass B4:bass-soft C5:bass C5:bass C5:bass C5:bass-soft C5:bass C5:bass C5:bass B4:bass-soft B4:bass B4:bass B4:bass",
   "noise": "kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open . kick .~f08 open~f07 . kick . open~f08 .~f07 kick . open .~f08 kick~f07 . open . kick~f08 .~f07 open ."
  },
  "P19": {
   "p1": "G6:lead - E6:lead - E5:lead E5:lead - E5:lead E5:lead - E5:lead E5:lead G5:lead G5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . . . . . . G5:lead G5:lead - G5:lead G5:lead - G5:lead G5:lead F#5:lead F#5:lead E5:lead E5:lead - . B4:lead B4:lead C5:lead C5:lead B4:lead B4:lead A#4:lead A#4:lead B4:lead B4:lead - . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . - . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft .",
   "wave": "- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": "kick .~f08 open~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 ."
  },
  "P20": {
   "p1": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "p2": "- . . . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . C5:soft . C5:soft . C5:soft . C5:soft . B4:soft . B4:soft . B4:soft . B4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . E4:soft . . . . . . . - . . .",
   "wave": ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .",
   "noise": ". . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07 . . . .~f08 .~f07"
  }
 },
 "order": [
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "P13",
  "P14",
  "P15",
  "P16",
  "P17",
  "P18",
  "P19",
  "P20"
 ]
};
